### ISSUE TITLE
[Bug] Docker Caddy IP Forwarding Headers

### ISSUE THREAD

**Issue by jnortell** [mealie-recipes/mealie#2407] opened 2023-06-02 17:03 UTC
Continuation of the original issue detailed in this PR: #2365 

When attempting to use a fail2ban regex filter on the "Incorrect username or password from *" log, the log always shows the internal IP of the front-end docker container.

From @hay-kot
This is likely due to a mis-configuration on the internal proxy that we use here https://github.com/hay-kot/mealie/blob/mealie-next/docker/frontend.Caddyfile
Probably just need to adjust it to forward the headers from the original request.

From @jecorn 
...But the caddy docs suggest that it should be easy to do add the relevant IP forwarding....

Issue created at the request of @jecorn

**Comment by jecorn** [comment] 2023-06-02 18:01
This is my bad. I wrote and tested the IP logging code on a bare metal dev instance, forgetting that networking is different in a docker container. I’ll take care of this next week.

**Comment by jecorn** [comment] 2023-06-04 15:53
Hmm. I need a hint from someone who uses the mealie docker dev container. I just confirmed that bare metal dev instance correctly gets IPs from two different machines (because there's no forwarding from outside a container to inside).. 

But when I tried to then recreate the problem with a docker dev container, I got stuck. I can access the container on the machine running the dev container via localhost:3000 or localhost:9000/docs. And in that case, the container reports failed logins as coming from 127.0.0.1, and not the docker network. But unlike the bare metal dev instance, the container seems to not be listening to other machines coming from outside localhost. A separate laptop that successfully connects to the bare metal dev instance can't do so for the docker dev instance. So I can't yet make sure that any changes I made are actually working.

Can someone working with docker dev give me a hint here about getting it to listen on the network? @hay-kot ?

**Comment by jnortell** [comment] 2023-06-04 16:42
> Hmm. I need a hint from someone who uses the mealie docker dev container. I just confirmed that bare metal dev instance correctly gets IPs from two different machines (because there's no forwarding from outside a container to inside)..
> 
> But when I tried to then recreate the problem with a docker dev container, I got stuck. I can access the container on the machine running the dev container via localhost:3000 or localhost:9000/docs. And in that case, the container reports failed logins as coming from 127.0.0.1, and not the docker network. But unlike the bare metal dev instance, the container seems to not be listening to other machines coming from outside localhost. A separate laptop that successfully connects to the bare metal dev instance can't do so for the docker dev instance. So I can't yet make sure that any changes I made are actually working.
> 
> Can someone working with docker dev give me a hint here about getting it to listen on the network? @hay-kot ?

I'm unsure what exactly is being asked, so my apologies if this is irrelevant information. I'm able to access my container via another computer on the local network with 192.168.x.x:9925

Here is my docker compose setup:
```
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-nightly
    container_name: mealie-frontend
    environment:
      - API_URL=http://mealie-api:9000
    restart: unless-stopped
    ports:
      - "9925:3000"
    volumes:
      - /path_to_data/mealie:/app/data/
    depends_on:
      - mealie-api
    networks:
      - <REDACTED>

  mealie-api:
    image: hkotel/mealie:api-nightly
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /path_to_data/mealie:/app/data/
    environment:
      - ALLOW_SIGNUP=false
      - PUID=<REDACTED>
      - PGID=<REDACTED>
      - TZ=America/New_York
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - DEFAULT_EMAIL=<REDACTED>
      - DEFAULT_GROUP=Home
      - BASE_URL=<REDACTED>
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_FROM_NAME=<REDACTED>
      - SMTP_AUTH_STRATEGY=TLS
      - SMTP_FROM_EMAIL=<REDACTED>
      - SMTP_USER=<REDACTED>
      - SMTP_PASSWORD=<REDACTED>
    restart: unless-stopped
    networks:
      - <REDACTED>
```

**Comment by jnortell** [comment] 2023-06-04 16:44
> Hmm. I need a hint from someone who uses the mealie docker dev container. I just confirmed that bare metal dev instance correctly gets IPs from two different machines (because there's no forwarding from outside a container to inside)..
> 
> But when I tried to then recreate the problem with a docker dev container, I got stuck. I can access the container on the machine running the dev container via localhost:3000 or localhost:9000/docs. And in that case, the container reports failed logins as coming from 127.0.0.1, and not the docker network. But unlike the bare metal dev instance, the container seems to not be listening to other machines coming from outside localhost. A separate laptop that successfully connects to the bare metal dev instance can't do so for the docker dev instance. So I can't yet make sure that any changes I made are actually working.
> 
> Can someone working with docker dev give me a hint here about getting it to listen on the network? @hay-kot ?

and my mealie.subdomain.conf file for nginx reverse proxy in SWAG container:

```
server {
listen 443 ssl http2;
listen [::]:443 ssl http2;

    server_name mealie.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;
    
    if ($lan-ip = yes) { set $geo-whitelist yes; }
    if ($geo-whitelist = no) { return 404; }


    location / {

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app mealie-frontend;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

            }

}

```

**Comment by jecorn** [comment] 2023-06-04 17:43
All good. This is a question I have about something called a “dev container” in vscode. I’m not quite sure how the container is configured. But thanks for the info, which might help debug if I run into something funny.

**Comment by jecorn** [comment] 2023-06-04 21:00
Wow. This is tricker than I thought. 

Just changing the caddyfile won't fix things, because X-Forwarded-For is already on by default and even adding X-Real-IP doesn't fix things. Also, requests all eventually go  through the API backend. So Gunicorn/uvicorn need to pass on the forwarded IPs via the headers. This is done via a command line switch that defines IP addresses to trust for sources of headers. But for some reason the even after complete whitelisting the relevant headers are never getting sent to FastAPI.  I'm heading to bed now, but will keep fiddling later.

(I figured out the container port thing through the vscode dev container appPort settings. But I think the real problem is that gunicorn isn't trusting forwarded headers.)

**Comment by jnortell** [comment] 2023-06-05 00:00
> Wow. This is tricker than I thought.
> 
> Just changing the caddyfile won't fix things, because X-Forwarded-For is already on by default and even adding X-Real-IP doesn't fix things. Also, requests all eventually go through the API backend. So Gunicorn/uvicorn need to pass on the forwarded IPs via the headers. This is done via a command line switch that defines IP addresses to trust for sources of headers. But for some reason the even after complete whitelisting the relevant headers are never getting sent to FastAPI. I'm heading to bed now, but will keep fiddling later.
> 
> (I figured out the container port thing through the vscode dev container appPort settings. But I think the real problem is that gunicorn isn't trusting forwarded headers.)

Jeez, I had no clue that this simple issue would turn into such a mission 🤣 
I really can’t thank you enough though for your continued support, it’s incredible dedication and you seem very talented at what you do!! Thank you again 😄

**Comment by jecorn** [comment] 2023-06-05 03:20
I didn’t mean to make you feel self-conscious about this. It’s actually only taking this long because I’m a novice at developing for docker. Once I get a clue, it will be something like a 1 line fix. All good!

**Comment by jnortell** [comment] 2023-06-05 03:30
> I didn’t mean to make you feel self-conscious about this. It’s actually only taking this long because I’m a novice at developing for docker. Once I get a clue, it will be something like a 1 line fix. All good!

You’re very humble, I appreciate the time and effort nonetheless!

**Comment by jecorn** [comment] 2023-06-05 06:51
@hay-kot I'm reading through the repo to reverse engineer the various entry points for mealie that might affect forwarding the correct IP. I just want to double-check that I have things right, so that once I have a fix I put it everywhere necessary.

- Backend "normal" container comes in through `api.Dockerfile -> docker/api.entry.sh`, which either starts gunicorn or uvicorn depending on an environment variable*. Command line variables set separately per each.
- Omni container comes in through `omni.Dockerfile -> docker/omni.entry.sh`, which also either starts gunicorn or uvicorn. Command line variables set separately per each and independently of the normal backend settings.
- Dev instance (either bare metal or docker) comes in through `make backend -> mealie/app.py`, which starts uvicorn using its own set of options that are not in sync with those in the production containers (e.g. `forwarded_allow_ips="*"` in the dev instance, but not in production)

Do I have that right?

*note: docs say that gunicorn is off by default, but in `docker/docker-compose.yml` and `docker/omni.docker-compose.yml` this seems to be default true?

**Comment by jecorn** [comment] 2023-06-05 15:08
It turns out that docker's ability to pass on the original IP via writing a header is linked to the platform that docker runs on. This has been true since 2016 and seems to still be true today. Original IP forwarding can work automagically for linux. But does not work on Mac or Windows. I'm developing on Mac, which explains why my fix that *should* have been writing X-Forward-For in uvicorn was not doing so.

One suggested workaround in the docker roadmap/issues is to have a reverse proxy running on the host to write the appropriate headers that would then be passed untouched through the docker container. Which is not a viable option for mealie (or really anyone).
https://github.com/docker/for-mac/issues/180
https://github.com/docker/roadmap/issues/157

So now we get to the real question. I can X-forward a dev stack from my linux server so that I can make sure the fix I already wrote works. But no matter what, the functionality of that fix will be linux-dependent. To me, this seems not great. I'm tempted to just revert IP logging entirely, since I think it would be better to not report anything than to report the wrong thing in a mysteriously platform-dependent manner. Note that `docker logs <mealie-api>` also currently shows all API requests as coming from within the docker container on linux. @hay-kot  what do you think? Revert IP logging to mealie.log, or make a linux-only solution?

**Comment by jnortell** [comment] 2023-06-05 16:36
> It turns out that docker's ability to pass on the original IP via writing a header is linked to the platform that docker runs on. This has been true since 2016 and seems to still be true today. Original IP forwarding can work automagically for linux. But does not work on Mac or Windows. I'm developing on Mac, which explains why my fix that _should_ have been writing X-Forward-For in uvicorn was not doing so.
> 
> One suggested workaround in the docker roadmap/issues is to have a reverse proxy running on the host to write the appropriate headers that would then be passed untouched through the docker container. Which is not a viable option for mealie (or really anyone). [docker/for-mac#180](https://github.com/docker/for-mac/issues/180) [docker/roadmap#157](https://github.com/docker/roadmap/issues/157)
> 
> So now we get to the real question. I can X-forward a dev stack from my linux server so that I can make sure the fix I already wrote works. But no matter what, the functionality of that fix will be linux-dependent. To me, this seems not great. I'm tempted to just revert IP logging entirely, since I think it would be better to not report anything than to report the wrong thing in a mysteriously platform-dependent manner. Note that `docker logs <mealie-api>` also currently shows all API requests as coming from within the docker container on linux. @hay-kot what do you think? Revert IP logging to mealie.log, or make a linux-only solution?

Not that my input is necessarily relevant to the end-decision, but I’ve been following this closely, so I’ll weigh in.

As a linux user, I would obviously prefer if the solution was implemented. Afaik, the majority of docker usage is on linux (I could definitely be wrong on this), and the IP logging works perfectly on the non-docker builds.

Perhaps you could create a docker environment variable that defaulted to false, or whitelist local IPs so the log line doesn’t output when the configuration is creating this issue?

In general, the main use of the log line seems to be for fail2ban, which by default configures itself to whitest those local IPs. While the current state doesn’t ban properly, it also does not falsely ban the internal docker IPs.

As I said before, I’m well aware of the fact that my opinion and needs have nothing to do with the development of this awesome software, and in no way will I be upset if you decide to revert IP logging. As always, thank you a ton for your awesome support!

**Comment by jnortell** [comment] 2023-06-06 19:09
Any news on a potential decision?

**Comment by hay-kot** [comment] 2023-06-06 19:30
> So now we get to the real question. I can X-forward a dev stack from my linux server so that I can make sure the fix I already wrote works. But no matter what, the functionality of that fix will be linux-dependent. To me, this seems not great. I'm tempted to just revert IP logging entirely, since I think it would be better to not report anything than to report the wrong thing in a mysteriously platform-dependent manner. Note that docker logs <mealie-api> also currently shows all API requests as coming from within the docker container on linux. @hay-kot what do you think? Revert IP logging to mealie.log, or make a linux-only solution?

I'd say 90% of users use linux, and anyone using fail2ban is also probably using linux? I'd say it's safe to implement a platform specific solution and add a note in the FAQ about the forwarding only working on linux based machines. 

We _could_ put the log behind a ENV variable flag or something, but I think that's probably unnecessary. Lot's of apps have similar problems like this. They'll just log the wrong value if the user doesn't set it up correctly.

**Comment by jnortell** [comment] 2023-06-09 21:02
> I can X-forward a dev stack from my linux server so that I can make sure the fix I already wrote works. 

Any news regarding the fix? @jecorn

**Comment by jecorn** [comment] 2023-06-10 04:07
The open pull request (see one line above) needs review/comment from hay-kot. After merging, it will get auto-built and released in nightly.

**Closed as completed** 2023-06-25 18:22 UTC
