### ISSUE TITLE
failed scrape from https://www.thekitchn.com with apparent valid JSON

### ISSUE THREAD

**Issue by eddpot** [mealie-recipes/mealie#1047] opened 2022-03-13 13:09 UTC
https://www.thekitchn.com/how-to-cook-classic-beef-brisket-in-the-slow-cooker-248238

```json
{
  "totalTime": "PT0S",
  "nutrition": {
    "saturatedFatContent": "15.7 g",
    "unsaturatedFatContent": "0.0 g",
    "carbohydrateContent": "46.1 g",
    "sugarContent": "28.4 g",
    "servingSize": "Serves 8",
    "proteinContent": "34.7 g",
    "fatContent": "43.5 g",
    "calories": "710 cal",
    "sodiumContent": "906.0 mg",
    "fiberContent": "4.4 g",
    "cholesterolContent": "0 mg",
    "@type": "NutritionInformation"
  },
  "description": "",
  "creator": {
    "@type": "Person",
    "name": "Meghan Splawn"
  },
  "datePublished": "2018-12-03T13:00:00-05:00",
  "brand": {
    "@type": "Thing",
    "name": "The Kitchn"
  },
  "recipeCuisine": [
    "Jewish"
  ],
  "dateCreated": "2018-12-03T13:00:00-05:00",
  "aggregateRating": {
    "ratingCount": 21,
    "@type": "AggregateRating",
    "ratingValue": 3.8
  },
  "recipeInstructions": [
    {
      "text": "Prepare the brisket, set it in the slow cooker. Pat the brisket dry with paper towels. If your brisket has a particularly thick fat cap, you can remove it now — I almost never bother, though, as the fat makes for an even more luxurious brisket. Sprinkle the brisket on all sides with 1 teaspoon of the salt. Place it in a 6-quart or larger slow cooker.",
      "image": null,
      "@type": "HowToStep",
      "name": "Step 1"
    },
    {
      "text": "Brown the onions and garlic over medium-high heat. Heat the oil in a large frying pan over medium-high heat until shimmering. Add the onions and cook until softened and beginning to brown and char in some spots, about 8 minutes. Add the garlic and cook until fragrant, about 2 minutes more.",
      "image": null,
      "@type": "HowToStep",
      "name": "Step 2"
    },
    {
      "text": "Add the spices and cook until fragrant. Add the smoked paprika, black pepper, thyme, oregano, and remaining 1 teaspoon salt and cook, stirring occasionally, until very fragrant, about 1 minute.",
      "image": null,
      "@type": "HowToStep",
      "name": "Step 3"
    },
    {
      "text": "Move the onions and garlic to the slow cooker, covering the brisket. Carefully transfer the onions over the brisket.",
      "image": null,
      "@type": "HowToStep",
      "name": "Step 4"
    },
    {
      "text": "Deglaze the pan with the beef broth, then add the sauce ingredients and bring to a simmer. Return the pan to medium-high heat, add the broth, and use a spatula or wooden spoon to scrape all the lovely browned bits up off the bottom of the pan. Add the ketchup, brown sugar, and tomato paste, and stir to combine. Bring the mixture to a simmer, then pour over the onions and brisket.",
      "image": null,
      "@type": "HowToStep",
      "name": "Step 5"
    },
    {
      "text": "Cover and cook on low for 6 to 8 hours. Add the potatoes and carrots to the slow cooker, tucking them around the brisket. Cover and cook on the LOW setting for 6 to 8 hours. The brisket is done when it easily shreds when pulled, but it shouldn’t be falling apart.",
      "image": null,
      "@type": "HowToStep",
      "name": "Step 6"
    },
    {
      "text": "Serving and storing the brisket. Transfer the brisket to a clean cutting board. If desired, use a spoon to scrape the fat cap off. Now you can slice and serve the brisket immediately, or slice the brisket and return it to the slow cooker to cool and then refrigerate — this is ideal for serving the dish to guests or if you’d like to remove more fat from the dish since it will harden. Serve the brisket with the potatoes, carrots, and a generous spoonful of the cooked onion and sauce.",
      "image": null,
      "@type": "HowToStep",
      "name": "Step 7"
    }
  ],
  "HowtoTip": {
    "text": "Make ahead: The brisket can be cooked up to 3 days in advance. Store the brisket and vegetables covered with the gravy. Reheat in the slow cooker or in a baking dish covered with aluminum foil in a low oven.Storage: Leftovers keep well for up to 5 days. Store the beef covered in extra gravy to keep the meat moist.Kosher: For kosher cooks, make sure the ketchup is corn-syrup free."
  },
  "articleSection": "Recipes",
  "keywords": [
    "beef",
    "Cooking Lessons from The Kitchn",
    "Dairy-Free",
    "dinner",
    "garlic",
    "Gluten-Free",
    "How To",
    "Keeps Well",
    "Main Dish",
    "Make Ahead",
    "Meat Tutorials",
    "Nut-Free",
    "oils",
    "onions",
    "Party Food",
    "passover",
    "Pinterest",
    "pot roast",
    "recipe",
    "Root Vegetables",
    "Rosh Hashanah",
    "Slow Cooker",
    "spices",
    "splash",
    "sugar",
    "purpose:search",
    "platform:search",
    "course:main dish",
    "dishtype:meat dish",
    "dishtype:pot roast",
    "cuisine:jewish",
    "mainingredients:meat",
    "mainingredients:beef",
    "method:cooking appliance",
    "method:slow cooker",
    "diet:dairy-free",
    "diet:gluten-free",
    "meal:dinner",
    "updated:2020-01-29"
  ],
  "suitableforDiet": "https://schema.org/GlutenFreeDiet,https://schema.org/LowLactoseDiet",
  "thumbnailUrl": "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_768/k%2Farchive%2F27d75d42fa7ae63a4aa8e2b698ae95fce389f888",
  "recipeCategory": [
    "Main dish",
    "Dinner",
    "Pot roast",
    "Meat dish"
  ],
  "dateModified": "2020-01-29T01:01:37-05:00",
  "publisher": {
    "logo": {
      "url": "https://www.thekitchn.com/static/logos/publisher-logo.png",
      "width": 180,
      "@type": "ImageObject",
      "height": 46
    },
    "@type": "Organization",
    "name": "Apartment Therapy, LLC."
  },
  "name": "How To Cook Classic Beef Brisket in the Slow Cooker",
  "author": {
    "URL": "https://www.thekitchn.com/authors/meghan-splawn",
    "description": "Meghan was the Food Editor for Kitchn's Skills content. She's a master of everyday baking, family cooking, and harnessing good light. Meghan approaches food with an eye towards budgeting — both time and money — and having fun. Meghan has a baking and pastry degree, and spent the first 10 years of her career as part of Alton Brown's culinary team. She co-hosts a weekly podcast about food and family called Didn't I Just Feed You.",
    "@type": "Person",
    "name": "Meghan Splawn"
  },
  "url": "https://www.thekitchn.com/how-to-cook-classic-beef-brisket-in-the-slow-cooker-248238",
  "image": [
    {
      "url": "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_16:9/k%2Farchive%2F27d75d42fa7ae63a4aa8e2b698ae95fce389f888",
      "@type": "ImageObject"
    },
    {
      "url": "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_4:3/k%2Farchive%2F27d75d42fa7ae63a4aa8e2b698ae95fce389f888",
      "@type": "ImageObject"
    },
    {
      "url": "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2Farchive%2F27d75d42fa7ae63a4aa8e2b698ae95fce389f888",
      "@type": "ImageObject"
    }
  ],
  "recipeIngredient": [
    "1  (3-pound) beef brisket (preferably flat cut)",
    "2 teaspoons kosher salt, divided",
    "3 tablespoons vegetable oil",
    "3  large sweet onions, thinly sliced",
    "6 cloves garlic, minced",
    "1 teaspoon smoked paprika",
    "1 teaspoon freshly ground black pepper",
    "1 teaspoon dried thyme",
    "1 teaspoon dried oregano",
    "2 cups low-sodium beef broth",
    "1/2 cup ketchup (see Recipe Notes)",
    "1/2 cup packed light brown sugar",
    "1 tablespoon tomato paste",
    "1 pound red potatoes, cut into 2-inch pieces",
    "1 pound carrots, peeled and cut into 1-inch pieces"
  ],
  "headline": "How To Cook Classic Beef Brisket in the Slow Cooker",
  "recipeYield": 8,
  "mainEntityOfPage": "https://www.thekitchn.com/how-to-cook-classic-beef-brisket-in-the-slow-cooker-248238",
  "@context": "https://schema.org",
  "@type": "Recipe"
}
```

**Comment by mijdavis2** [comment] 2022-03-22 17:04
Dupe of https://github.com/hay-kot/mealie/issues/978

**Comment by hay-kot** [comment] 2022-05-05 05:02
Closing duplicate issue

**Closed as completed by hay-kot** 2022-05-05 05:02 UTC
Labels: fixed in v1
