### ISSUE TITLE
[BUG] - MIGRATION : Cannot restore Mealie 1.0beta backup to Mealie 1.0

### ISSUE THREAD

**Issue by Sphinkie** [mealie-recipes/mealie#2985] opened 2024-01-13 15:43 UTC
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

After restoring the backup from Mealie 1.0.0 beta :
- no recepies are migrated
- the Mealie database seems corrupt : Before restore, the menu "Site settings"  shows "your version is uptodate". After restore, it shows "Your current version (null) does not match the latest release. Considering updating to the latest version (null). "

### Steps to Reproduce

1) In Mealie version (v1.0.0beta-5) , connect as as admin, goto Settings → Backup and create a backup
2) Connect to a new fresh docker with the latest version (nightly mealie docker - 13-jan-2024) as "changeme@example"
3) copy the zip file from the backups directory, to the data/backups forlder of the new docker
4) Goto Settings → Backup menu and restore the backup
5/ Accept the warning message popup

### Please provide relevant logs

See attached logs

[_Mealie_logs.txt](https://github.com/mealie-recipes/mealie/files/13928631/_Mealie_logs.txt)

### Mealie Version

Mealie-DB	     healthy	mealie	postgres	                                                2024-01-13
Mealie	             healthy	mealie	ghcr.io/mealie-recipes/mealie:nightly	2024-01-13

### Deployment

Docker (Synology)

**Comment by michael-genson** [comment] 2024-01-13 15:49
Do you have logs from when you did the migration? And, can you post your backup file?

**Comment by Sphinkie** [comment] 2024-01-13 17:51
Here are the logs of the Mealie docker and the Database docker during the attempt of restoring the backup file.

[_Mealie_logs(2).txt](https://github.com/mealie-recipes/mealie/files/13929019/_Mealie_logs.2.txt)
[_Mealie-DB_logs(2).txt](https://github.com/mealie-recipes/mealie/files/13929021/_Mealie-DB_logs.2.txt)

(in the "Settings → Maintenance → Logs" menu, there is nothing)

and here is the backup file:

[mealie_2024.01.13.11.51.45.zip](https://github.com/mealie-recipes/mealie/files/13929030/mealie_2024.01.13.11.51.45.zip)

Thanks

**Comment by michael-genson** [comment] 2024-01-13 18:00
Hmm, I'm having no issues loading your backup. Can you create a fresh instance and share your logs? I want to check the git hash which should be in the startup logs

**Comment by michael-genson** [comment] 2024-01-13 18:05
I'm also not seeing the migration in the logs, so if you're able to attempt the restore again and provide those logs that would be helpful. Those logs should start with:
```
Running upgrade  -> 6b0f5f32d602, Initial tables
Running upgrade 6b0f5f32d602 -> 263dd6707191, convert quantity from integer to float
Running upgrade 263dd6707191 -> f1a2dbee5fe9, Add original_text column to recipes_ingredients
...
```

**Comment by Sphinkie** [comment] 2024-01-13 18:17
Here are the logs when a fresh instance is created.
(I also add the compose script, just in case)

[_Mealie_logs.creation.log](https://github.com/mealie-recipes/mealie/files/13929104/_Mealie_logs.creation.log)
[_Mealie-DB_logs.creation.log](https://github.com/mealie-recipes/mealie/files/13929105/_Mealie-DB_logs.creation.log)
[mealie-1.0-docker.txt](https://github.com/mealie-recipes/mealie/files/13929106/mealie-1.0-docker.txt)

**Comment by Sphinkie** [comment] 2024-01-13 18:35
Sorry: I just saw that the logs have only 100 lines length.
I will add the full logs in a minute.

**Comment by michael-genson** [comment] 2024-01-13 18:35
Okay cool you're on a new-enough version that it's not a version issue. It looks like one of the logs you posted earlier is cut off - can you try restoring your backup, waiting for it to fail, then sharing those logs?

Mostly what I'm looking for is where in the migration process it fails, and what the failure is. Normally I'm able to reproduce with your backup file, but it seems to be restoring fine on my dev instance (though my dev instance uses sqlite so it's possibly a postgres-specific problem)

**Comment by Sphinkie** [comment] 2024-01-13 18:44
18:10 = creation of the dockers  (the logs of the very begining are still missing:  but I will redo the creation)
18:29 = restore of the backup 

[_Mealie_logs(4).txt](https://github.com/mealie-recipes/mealie/files/13929167/_Mealie_logs.4.txt)
[_Mealie-DB_logs(4).txt](https://github.com/mealie-recipes/mealie/files/13929168/_Mealie-DB_logs.4.txt)

**Comment by michael-genson** [comment] 2024-01-13 18:46
Perfect, that has exactly what I needed, thanks! Investigating now

**Comment by michael-genson** [comment] 2024-01-13 19:06
The issue is related to this:
https://github.com/mealie-recipes/mealie/issues/2499

Somehow your database contains foreign keys that don't exist. This _shouldn't_ be possible, but I've seen it in a few instances (including my own because I used to use sqlite and it doesn't care nearly as much about foreign key errors). AFAIK there's no easy way to list all of them, but the first one that threw an error was:

```
(psycopg2.errors.ForeignKeyViolation) insert or update on table "recipe_nutrition" violates foreign key constraint "recipe_nutrition_recipe_id_fkey"
Key (recipe_id)=(e1346ad9-0ed3-44d3-9935-462b362c99d1) is not present in table "recipes"
```

I'm going to attempt to write a general fix for this, but it might take me a while. While this will _definitely_ be a pain, what you can do in the meantime is manually fix your data:

1. In your backup zip there is a `database.json` file. Extract that and open it in any text editor
2. Search for the foreign key raising the error (in this case it's `e1346ad9-0ed3-44d3-9935-462b362c99d1`). Note in the data JSON it will remove the dashes, so in this case search for `e1346ad90ed344d39935462b362c99d1`
3. Delete all objects that reference this (i.e. wherever that id appears, delete everything between the nearest brackets `{...}`
4. Replace the `database.json` file in your zip, then try importing the backup
5. If another error is raised with a new id, repeat steps 2-4

Or, alternatively, just wait for a fix. Hopefully I can figure one out

**Comment by Sphinkie** [comment] 2024-01-14 08:13
Thank you very much for your answers.

PS: I have remove the first  problematic id (2 occurences) and then there is a second problematic id with 103 occurences. I will try to remove it with a script, otherwise I will wait for the fix.

**Comment by michael-genson** [comment] 2024-01-14 15:55
No problem. Yeah I had to do something similar with my data as well. Be sure to keep a backup of the original data in case you delete something important by accident.

**Comment by michael-genson** [comment] 2024-01-15 00:24
FYI if you haven't gone through and sanitized your data yet, looks like https://github.com/mealie-recipes/mealie/pull/2986 is going to do it for you automatically during restore 🤞 You can try pulling the branch locally and testing it yourself, or wait for it to get merged

**Closed as completed** 2024-01-16 22:12 UTC
Labels: bug, bug: confirmed

**Comment by michael-genson** [comment] 2024-01-16 22:14
Once the newest nightly version is published (usually within 2 hours of merging a PR), try pulling it and seeing if you're able to upgrade. You can also keep an eye on the #nightly channel in Discord, which receives a notification every time there's a new nightly build

**Comment by Sphinkie** [comment] 2024-01-17 21:02
I have pulled the nightly version, and then made a migration.
The restoration of the backup of v1.0beta5 worked fine.
Now I have all the recipes (and users) present in the new Mealie 1.0 docker.
I checked only few recipes, but everything seems ok.
Thanks a lot.

**Comment by michael-genson** [comment] 2024-01-17 21:03
Wonderful! Glad to hear!
