### ISSUE TITLE
[BUG] - Data Management - Recipe Data - Tag / Category Action Showing Same List 

### ISSUE THREAD

**Issue by NP00111** [mealie-recipes/mealie#3953] opened 2024-07-28 20:07 UTC
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When I go to Data Management - Recipe Data, I want to set the Category and Tags.  But both are bringing the list.  Category is showing the Tags List for selection.  

### Steps to Reproduce

1. Go to Data Management
2. Select Recipe Data
3. Select Multiple Recipes
4. Select Action and then Category, the dropdown list shows tags.

### Please provide relevant logs

None

### Mealie Version

nightly
Build Tag - [def346d16d4d0a8dbe9128af12625b00572bb184]
(https://github.com/mealie-recipes/mealie/commit/def346d16d4d0a8dbe9128af12625b00572bb184)

### Deployment

Docker (Linux)

### Additional Deployment Details

None

**Comment by NP00111** [comment] 2024-07-28 20:07
Reproduced in Demo Site

**Comment by Kuchenpirat** [comment] 2024-07-29 08:14
Can't reproduce it on my own instance but can reproduce it on the demo instance. 
So there is definitfly something wrong. It will always just use the first choosen list (tags or categories) and not switch to the new one. So you can get it to only display categories, or only display tags depending on what you have chosen first.

**Comment by boc-the-git** [comment] 2024-07-29 10:31
What database are you using @NP00111? How about you @Kuchenpirat? Wondering if that's a factor..

**Comment by Kuchenpirat** [comment] 2024-07-29 10:34
Sqlite for me. The demo does also use Sqlite, so that should not be the issue. 
My guess is that we need to do some cleanup in the frontend. It works as expected the first time every time and gets confused afterwards.

**Comment by michael-genson** [comment] 2024-07-29 15:57
Is this a duplicate of https://github.com/mealie-recipes/mealie/issues/2200?

**Comment by boc-the-git** [comment] 2024-07-30 07:05
> Is this a duplicate of #2200?

Sounds like it from Kuchens description.

**Closed as completed by boc-the-git** 2024-07-30 07:05 UTC
Labels: bug, bug: confirmed, triage
