### ISSUE TITLE
Server error Connection Refused when using IPV6

### ISSUE THREAD

**Issue by Zerwin** [mealie-recipes/mealie#2440] opened 2023-07-04 20:15 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

After pulling the latest Omni build and running it, my existing (already migrated) version of mealie stopped working. 

The browser just shows an error message:
![image](https://github.com/hay-kot/mealie/assets/46265592/c5810e3d-a5ae-4390-aa63-251fdbc9ab51)

And looking in the logs, there is just an ECONNREFUSED error.

```
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)

 ERROR  connect ECONNREFUSED ::1:3000

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1481:16)
  ```
 On every refresh, another ECONNREFUSED  gets added to the log, always with the same message.

### Deployment

Docker (Linux)

### Mealie Version

omni-nightly

**Comment by nebuohyrrah** [comment] 2023-07-07 08:14
I have the same experience. Seems to be ipv6 related.
Quick fix for now is deleting `::1     localhost ip6-localhost ip6-loopback` from the /etc/hosts file inside the container.

**Comment by Cyphrz** [comment] 2023-07-08 21:44
Same issue, oddly enough it just started happening without any changes done.

**Comment by katiuskt** [comment] 2023-07-30 12:46
Same issue here

> I have the same experience. Seems to be ipv6 related. Quick fix for now is deleting `::1 localhost ip6-localhost ip6-loopback` from the /etc/hosts file inside the container.

@nebuohyrrah : Please, can you elaborate a little bit more how to edit that /etc/hosts file? It seems there is no 'vi' or 'nano' editor installed and tried to 'apt install' them the root password is needed and I did not set it anywhere.

Thanks in advance!

UPDATE: Nevermind, I found out the way. In case someone else faces the same issue, until it is fixed the workaround mentioned by @nebuohyrrah works. Steps I followed:
1. Start mealie container
2. Outside of mealie container, set the password you want for the root user inside the mealie container: `docker exec -it -u 0 mealie_container_name your_desired_root_new_password`
3. Open a mealie container terminal
4. Grant root user access (using "your_desired_root_new_password"), update apt and install nano
5. Edit the /etc/hosts file and comment the line mentioned above `::1     localhost ip6-localhost ip6-loopback`

**Comment by Zerwin** [comment] 2023-08-01 09:15
I finally managed to solve the problem without going into the container and editing the hosts file.

Docker has the `net.ipv6.conf.all.disable_ipv6=1` parameter which disables IPV6 for a container. I added to my compose file 
```
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
```
and the container just works again. Will have to observe it for a while if it is a permanent fix or will reset itself like the previous one did.

**Comment by stappel** [comment] 2023-08-08 09:14
Both workarounds did not work for me:

```mealie         | INFO:     Application startup complete.
mealie         | INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
mealie         |
mealie         |  ERROR  connect EADDRNOTAVAIL ::1:80 - Local (:::0)
mealie         |
mealie         |   at internalConnect (node:net:1060:16)
mealie         |   at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
mealie         |   at node:net:1244:9
mealie         |   at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
mealie         |
```

**Comment by 2fst4u** [comment] 2023-08-16 06:03
Docker specific fixes don't work for kubernetes. I get the same issue on my k3s cluster unfortunately.

I was able to workaround this in kubernetes by mounting a custom hosts file as a subpath into the pod.

**Comment by krair** [comment] 2023-08-25 09:44
A little digging showed that this is an issue with Nuxt v2.X. The fix appears to be merged into v3: https://github.com/nuxt/nuxt/issues/13964

In the meantime, an easy fix is to simply set the env variable `API_URL` to a hard-coded ipv4 address: `http://127.0.0.1:9000`. This works because we can override the default value of the Nuxt config file which currently uses `http://localhost:9000` - which resolves to an ipv6 address.

**Comment by 2fst4u** [comment] 2023-09-12 05:17
> A little digging showed that this is an issue with Nuxt v2.X. The fix appears to be merged into v3: https://github.com/nuxt/nuxt/issues/13964
> 
> In the meantime, an easy fix is to simply set the env variable `API_URL` to a hard-coded ipv4 address: `http://127.0.0.1:9000`. This works because we can override the default value of the Nuxt config file which currently uses `http://localhost:9000` - which resolves to an ipv6 address.

This worked for me, thanks. Much more elegant workaround than mounting a different etc/hosts.

**Comment by hay-kot** [comment] 2024-01-20 16:16
Hey! Our deployment stack has changed. We are no longer using Nuxt. As such I'm going to close this as tentatively fix. If the issue is still present in the latest deployment. Please fill out another issue. Thanks!

**Closed as completed by hay-kot** 2024-01-20 16:16 UTC
