### ISSUE TITLE
Users from seperate groups can't see recipes that are public or shared.

### ISSUE THREAD

**Issue by Manny8787** [mealie-recipes/mealie#2931] opened 2024-01-09 18:07 UTC
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Users from a guest group can't see recipes from Home group, show recipes to other groups is enabled.

### Steps to Reproduce

Create user in new group, log in with new user. 

### Please provide relevant logs

**Details**
Version: v1.0.0-RC2
Build: c9852daf0e213dc4cadf97971c7787cf6fc66dfc
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.52.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volume: success

### Mealie Version

**Details**
Version: v1.0.0-RC2
Build: c9852daf0e213dc4cadf97971c7787cf6fc66dfc
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.52.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volume: success

### Deployment

Other (please specify below)

### Additional Deployment Details

Qnap container station

**Comment by michael-genson** [comment] 2024-01-09 18:30
This is intended behavior, groups are isolated instances and don't interact with each other.
Users can browse other group sites the same way a non-logged-in user can, by going directly to the group URL:

`https://your-url.tld/g/yourGroupSlug`

**Comment by Kuchenpirat** [comment] 2024-01-09 18:30
Extending on what @michael-genson said:
There is a feature mapped out that would propably implement what you are looking for (see #2134), but there has not yet been work done to implement this afaik.

**Comment by Manny8787** [comment] 2024-01-09 18:33
Ohhh ok gotcha. 
I've been pulling my hair out. 
So I don't need to start a new thread and maybe able to have a quick reply. 
Is there size limits to upload a profile photo? 
And is there any way if I  was to import a URL of a recipe from a US site, to have the measurements converted to metric? 
Thank you.

**Comment by Kuchenpirat** [comment] 2024-01-09 18:36
1. I don't think so on the file limit one, as i was able to upload a DSLR pic. 
2. No there is no automatic unit conversion implemented in mealie.

**Comment by Manny8787** [comment] 2024-01-09 18:38
Thank you. 
1. hmm not sure what I am doing worng then, the photo uploads but then nothing gets saved and after I update and reload the page it is still the same. 
2. ok

**Comment by Kuchenpirat** [comment] 2024-01-09 18:39
are you using a special file format? Those can sometimes cause an exeption.

**Comment by Kuchenpirat** [comment] 2024-01-09 18:40
I'll close this as the issue described is intendet behaviour.

**Comment by Manny8787** [comment] 2024-01-09 18:41
thank you

**Closed as not planned by Kuchenpirat** 2024-01-09 18:40 UTC
Labels: bug, triage
