### ISSUE TITLE
[v1.0.0b] - Leaving quantity blank in parser fails silently

### ISSUE THREAD

**Issue by geoffbon** [mealie-recipes/mealie#1238] opened 2022-05-16 16:38 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When importing a recipe, then clicking 'parse' to edit the ingredient list, if one of the quantities is left blank (actually blank, not set to zero) then clicking 'save all', nothing appears to happen.  The user gets no error, and the ingredient list isn't saved.
The console shows the following:
![image](https://user-images.githubusercontent.com/54509333/168641505-81e1562b-6aa3-4c01-b083-8ebd268d22fd.png)

### Deployment

Other

### Deployment Details

Deployed using Kubernetes

**Comment by hay-kot** [comment] 2022-05-18 17:49
duplicate

#1231

**Comment by geoffbon** [comment] 2022-05-18 17:57
The linked issue says "does not allow to save ingredients with a quantity of 0".
For me, it lets me save with zero; just not with a blank value.

**Comment by newstatesolutions** [comment] 2022-05-24 12:56
This is not a duplicate of #1231 (that issue appears to be fixed), while this issue appears to be still broken.  They are different problems.

**Comment by newstatesolutions** [comment] 2022-05-24 16:08
Appears to be fixed in current build - can be closed now.

**Comment by hay-kot** [comment] 2022-05-24 16:09
Sorry about the confusion, thanks for following up!

**Closed as completed by hay-kot** 2022-05-24 16:09 UTC
