### ISSUE TITLE
[v1.0.0b] - Linking directly to specific tag/category page fails to render

### ISSUE THREAD

**Issue by epheterson** [mealie-recipes/mealie#1414] opened 2022-06-17 07:22 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

If you click on a tag or category to view a list of associated recipes, then either reload the page or use the URL in a new browser window, the page will fail to render properly and show no title or recipes.

This does reproduce on the demo site, e.g.
https://demo.mealie.io/recipes/categories/sandwich

### Deployment

Docker (Synology)

### Deployment Details

```
**Details**
Version: v1.0.0beta-3
Build: 56eb0bca7142715984c8028c4c881f086e979564
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.3.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: success
```

**Comment by hay-kot** [comment] 2022-06-18 00:31
Looks like this have been fixed in the nightly at some point... I've updated the beta and can't reproduce the issue.

**Closed as completed** 2022-06-19 18:11 UTC
Labels: bug
