### ISSUE TITLE
[v1.0.0b] - Duplicate sort button on overview recipes

### ISSUE THREAD

**Issue by Sennevds** [mealie-recipes/mealie#2215] opened 2023-03-07 10:55 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

There are 2 sort buttons on the recipe overview:
![image](https://user-images.githubusercontent.com/3531609/223402333-51302ad8-3852-4263-a94d-a7fdb480c6d9.png)
The top one works lower fires a request but no change in the UI

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment] 2023-03-07 16:03
Duplicate of

- #2194

**Closed as not planned** 2023-03-07 16:03 UTC
