### ISSUE TITLE
[BUG] - Items in shopping list not showing when added

### ISSUE THREAD

**Issue by kabatp** [mealie-recipes/mealie#4288] opened 2024-09-30 13:36 UTC
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When adding items to a shopping list, the items show up only for a brief moment before disappearing.

### Steps to Reproduce

1. Create a new shopping list
2. Push Add button
3. Fill Note and Qty
4. Push Save button

### Please provide relevant logs

Postgres:
2024-09-30 15:22:47.676156+02:002024-09-30T15:22:47.676156286+02:00
2024-09-30 15:22:47.676202+02:00PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-30 15:22:47.676213+02:002024-09-30T15:22:47.676213243+02:00
2024-09-30 15:22:47.910056+02:002024-09-30 15:22:47.910 CEST [1] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-09-30 15:22:47.910178+02:002024-09-30 15:22:47.910 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-09-30 15:22:47.910203+02:002024-09-30 15:22:47.910 CEST [1] LOG:  listening on IPv6 address "::", port 5432
2024-09-30 15:22:47.924104+02:002024-09-30 15:22:47.924 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-09-30 15:22:47.976648+02:002024-09-30 15:22:47.976 CEST [16] LOG:  database system was shut down at 2024-09-30 15:22:28 CEST
2024-09-30 15:22:48.045568+02:002024-09-30 15:22:48.045 CEST [1] LOG:  database system is ready to accept connections
2024-09-30 15:27:48.063082+02:002024-09-30 15:27:48.063 CEST [14] LOG:  checkpoint starting: time
2024-09-30 15:27:49.422676+02:002024-09-30 15:27:49.422 CEST [14] LOG:  checkpoint complete: wrote 14 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.203 s, sync=0.146 s, total=1.360 s; sync files=15, longest=0.040 s, average=0.010 s; distance=23 kB, estimate=23 kB
2024-09-30 15:32:48.460421+02:002024-09-30 15:32:48.460 CEST [14] LOG:  checkpoint starting: time
2024-09-30 15:32:50.795922+02:002024-09-30 15:32:50.795 CEST [14] LOG:  checkpoint complete: wrote 24 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=2.305 s, sync=0.021 s, total=2.336 s; sync files=20, longest=0.012 s, average=0.002 s; distance=76 kB, estimate=76 kB

Mealie:
2024-09-30 15:22:47.676156+02:002024-09-30T15:22:47.676156286+02:00
2024-09-30 15:22:47.676202+02:00PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-30 15:22:47.676213+02:002024-09-30T15:22:47.676213243+02:00
2024-09-30 15:22:47.910056+02:002024-09-30 15:22:47.910 CEST [1] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-09-30 15:22:47.910178+02:002024-09-30 15:22:47.910 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-09-30 15:22:47.910203+02:002024-09-30 15:22:47.910 CEST [1] LOG:  listening on IPv6 address "::", port 5432
2024-09-30 15:22:47.924104+02:002024-09-30 15:22:47.924 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-09-30 15:22:47.976648+02:002024-09-30 15:22:47.976 CEST [16] LOG:  database system was shut down at 2024-09-30 15:22:28 CEST
2024-09-30 15:22:48.045568+02:002024-09-30 15:22:48.045 CEST [1] LOG:  database system is ready to accept connections
2024-09-30 15:27:48.063082+02:002024-09-30 15:27:48.063 CEST [14] LOG:  checkpoint starting: time
2024-09-30 15:27:49.422676+02:002024-09-30 15:27:49.422 CEST [14] LOG:  checkpoint complete: wrote 14 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.203 s, sync=0.146 s, total=1.360 s; sync files=15, longest=0.040 s, average=0.010 s; distance=23 kB, estimate=23 kB
2024-09-30 15:32:48.460421+02:002024-09-30 15:32:48.460 CEST [14] LOG:  checkpoint starting: time
2024-09-30 15:32:50.795922+02:002024-09-30 15:32:50.795 CEST [14] LOG:  checkpoint complete: wrote 24 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=2.305 s, sync=0.021 s, total=2.336 s; sync files=20, longest=0.012 s, average=0.002 s; distance=76 kB, estimate=76 kB

### Mealie Version

App Version: 1.12.0
Chart Version: 1.0.25 

### Deployment

TrueNAS

### Additional Deployment Details

TrueNas Scale: Dragonfish-24.04.2.2

**Comment by michael-genson** [comment] 2024-09-30 15:12
Can you share your docker compose? Unsure if TrueNAS has that. If not, what timezone is your server in?

**Comment by kabatp** [comment] 2024-10-01 12:48
> Can you share your docker compose? Unsure if TrueNAS has that. If not, what timezone is your server in?

Timezone: 'Europe/Bratislava' timezone

Docker compose is not installed in APPS pods by default

**Comment by kabatp** [comment] 2024-10-01 12:54
Mealie app settings:

![storage](https://github.com/user-attachments/assets/8c7ff96f-738e-49fa-9d27-346738cc1f02)

![user](https://github.com/user-attachments/assets/9607238c-63ad-4bda-b698-1b08b7ba629f)

![config](https://github.com/user-attachments/assets/0e701970-3228-4ab4-9178-89845bf21882)

**Comment by michael-genson** [comment] 2024-10-01 14:34
I tried reproducing this locally with a db and client in that timezone and couldn't. Can you try switching your timezone to UTC and seeing if that fixes the problem?

**Comment by kabatp** [comment] 2024-10-01 21:53
> I tried reproducing this locally with a db and client in that timezone and couldn't. Can you try switching your timezone to UTC and seeing if that fixes the problem?

Changing the timezone to UTC did not help to resolve the issue

**Comment by michael-genson** [comment] 2024-10-01 23:10
Are you getting any server errors? Are you getting any client errors (e.g. F12 console in Chrome)?

**Comment by kabatp** [comment] 2024-10-02 07:37
> Are you getting any server errors? Are you getting any client errors (e.g. F12 console in Chrome)?

Console response when I push the add button:
![{5B4FFFA0-4E31-4D85-A0A6-4D174AF281CB}](https://github.com/user-attachments/assets/6a6bbb9f-cd61-4655-8336-087a947ac813)


There are no errors on the server side as far as I can check - the pods logs were attached in the post

**Comment by michael-genson** [comment] 2024-10-02 14:11
Can you share the response from the network request that contains the shopping list when you load the page? (should be sent to `.../api/groups/shopping/lists/{yourListId}`). I'm trying to see why your client is behind your shopping list

Also, are you able to query your db directly and see what the "created_at" and "update_at" values of your shopping list are? Wondering if they're getting stored in a weird way

**Comment by kabatp** [comment] 2024-10-02 15:03
Network response after pushing the Add button:

![{08F55E9D-A3C5-4732-B57F-BC8A21242ADC}](https://github.com/user-attachments/assets/04355ece-f6be-400e-b652-5b12f111d631)


When I opened the shopping list today, I found one checked item, and 1st item I added today was successfully added (the rest wasn't).

The response for the GET in 1st pic:
![{A6825864-2A26-4030-99DC-05C27C430083}](https://github.com/user-attachments/assets/64f394cd-8bd9-4530-b266-344a3b014704)


I can't give you pgsql results as pgAdmin on TrueNAS has some package chmod issue and cannot be deployed, but the created at and updated at are visible in GET response

**Comment by michael-genson** [comment] 2024-10-02 15:10
It looks like something is up with your server time. Can you check the current time on your machine and make sure it's correct?

Your timestamp of `2024-10-02T16:12:52.346148Z` is wrong (it's currently 15:09 UTC), it's an hour and several minutes ahead. If it had been exactly one or two hours I would think it's likely something wrong with Mealie, but an hour and several minutes is suspicious.

**Comment by kabatp** [comment] 2024-10-02 15:28
This is TrueNAS time 
![{4B946CAA-D7D4-4C26-8730-F77E21F6C2A3}](https://github.com/user-attachments/assets/c1757ade-6d4f-452c-bce4-42418324e916)


I tried to change the mealie timezone back to EUROPE/Bratislava, and in that case, the response is:
![{61960B1F-8715-42EF-9220-E3054FDAF3D3}](https://github.com/user-attachments/assets/ee1f21c1-a6f4-4a78-aeca-8e30d21563e3)

I would assume that the one hour would be the summer/winter time in Europe, but the minutes I am not able to justify

**Comment by michael-genson** [comment] 2024-10-02 15:33
Okay so somehow the timestamp is changing even though it's purportedly returning UTC time. Unfortunately I'll need to see how it's being stored in the database to diagnose what's going on there. Since the API is returning a time and calling it UTC, but it's not UTC, it's almost certainly reading something weird from the db.

The minutes being wrong is... weird, since your server time is correct.

**Comment by kabatp** [comment] 2024-10-03 08:33
Hey, I managed to get into the DB, what exactly do you need to see?

**Comment by michael-genson** [comment] 2024-10-03 14:00
If you could create a new shopping list, note the current time in UTC, then provide the created_at and update_at values from the database from that list. Hopefully that sheds some light on the issue.

**Comment by kabatp** [comment] 2024-10-03 14:14
The mealie instance is set up as follows
![{2062A727-FB01-49A1-9163-961823AB7525}](https://github.com/user-attachments/assets/35c7f3d1-31b3-4981-b2a1-78a7648e3659)


And I created new list:
![{E7D79378-F2AF-4D02-804B-2C3885F1F546}](https://github.com/user-attachments/assets/6d28935a-f2b0-4956-8861-610e5316475d)

The minutes are OK, but seems like the time is from TrueNAS Scale and not from the app settings

**Comment by kabatp** [comment] 2024-10-03 14:17
Created new one with UTC+2 setup and got following
![{26C69979-D021-4104-8839-3F4501C32C27}](https://github.com/user-attachments/assets/833a65cd-3e2f-4565-84c7-378bca2f6e0c)

**Comment by michael-genson** [comment] 2024-10-03 14:19
Okay so it's definitely being stored wrong in the database then, and it has no timezone. Let me look into this.

Side note, when you change the timezone in Mealie, are you rebuilding the container? Just changing the value won't have an effect on the instance.

**Comment by kabatp** [comment] 2024-10-03 14:23
A container is not rebuilt in the process of settings update in TrueNAS Scale, but it is restarted. The settings changes should take place after the restart of the container.

**Comment by michael-genson** [comment] 2024-10-03 14:25
I'm not familiar with TrueNAS, but restarting a docker container doesn't change environment variables, you have to rebuild the container

**Comment by kabatp** [comment] 2024-10-03 14:32
Timezone is not part of environment variables but direct settings in TrueNAS, even changing env variables in TrueNAS and restarting the container is enough to make a change.

**Comment by michael-genson** [comment] 2024-10-03 14:38
Are you not setting the TZ environment variable? Is TrueNAS using something else?
https://docs.mealie.io/documentation/getting-started/installation/backend-config/#general

Can you try setting the TrueNAS timezone, and the TZ environment variable, and then rebuild the container?

**Comment by kabatp** [comment] 2024-10-03 14:41
No, there is a direct setting for Timezone in the App setup
![image](https://github.com/user-attachments/assets/cdc85670-1d2e-481e-9ad2-a25eae9abc68)


Any other insert into the DB works - recipes, meal planners, cookbooks, organizers...

I tried to insert an item in the shopping list directly via DB and then the Item is shown in the Shopping List, but I cannot manipulate it in any way, not even check, or rename it

**Comment by michael-genson** [comment] 2024-10-03 14:44
![image](https://github.com/user-attachments/assets/f42574d2-c062-40c2-9e86-11e2ed18eb7e)

It looks like this is setting the timezone. Try setting this to UTC.

![image](https://github.com/user-attachments/assets/54577c5b-1db1-49a9-9870-ea50c3955f95)

Just for good measure, also add the `TZ` env var with the value `UTC`.

Then rebuild the container and see what happens.

**Comment by kabatp** [comment] 2024-10-03 14:49
I already tried changing the Timezone setting when creating UTC shopping list. This time I set up env variable to UTC and timezone to UTC, got this
![{A1C9F86A-B6F7-45E7-99A2-E2F6DA6F666F}](https://github.com/user-attachments/assets/03a4ecb2-2e0f-49a2-b202-a57cd1d6965a)

**Comment by kabatp** [comment] 2024-10-03 14:54
I changed the timezone of my TrueNAS Scale system and got the same results
![{54FA93BD-E3C6-4723-B71E-781FFDFC18F6}](https://github.com/user-attachments/assets/38e0a17b-af5c-4683-9266-13ce6fbd9e79)


Apparently none of these are taking the changes - I will try with a new instance of mealie set up with UTC timezone from scratch

**Comment by michael-genson** [comment] 2024-10-03 15:03
Okay I was _finally_ able to reproduce this. Looks like manually setting the postgres timezone to `Europe/Bratislava` and leaving Mealie as UTC triggers the issue. This confirms there's an issue going between the Python layer and the db layer.

I would guess that your idea of recreating the whole instance as UTC will fix it since it will (probably?) set postgres to UTC. Otherwise you can try manually switching it to UTC:

`SET timezone TO 'UTC'`

**Comment by michael-genson** [comment] 2024-10-03 16:05
https://github.com/mealie-recipes/mealie/pull/4310 should fix this, but in the meantime the above should resolve it for you. I'll keep this one open until you're able to confirm it's resolved.

**Comment by kabatp** [comment] 2024-10-04 06:30
Setting the DB timezone to UTC worked well, but I had to restart the container to reflect the changes.

I also installed a new instance to test it out. Yes, setting the timezone during installation to UTC worked well.

Thank you!

**Comment by michael-genson** [comment] 2024-10-04 14:25
Great to hear! I'll keep this open until https://github.com/mealie-recipes/mealie/pull/4310 is merged

**Closed as completed** 2024-10-06 06:30 UTC
Labels: bug, triage
