### ISSUE TITLE
Mealie not picking up on recipe

### ISSUE THREAD

**Issue by jaspermayone** [mealie-recipes/mealie#1070] opened 2022-03-19 00:48 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Mealie is not picking up on the recipe on [https://createplaytravel.com/treats-drinks/freeze-dried-raspberry-macarons/](https://createplaytravel.com/treats-drinks/freeze-dried-raspberry-macarons/)

### Deployment

Docker (Linux)

### Mealie Version

v0.5.6

**Comment by xxxserxxx** [comment] 2022-03-19 18:39
Mealie doesn't always successfully scrape, but lately I've been seeing something odd.  Take this recipe:

```
https://www.eatwell101.com/garlic-butter-chicken-bites-asparagus-recipe
```

There are **no** redirects -- it returns a 200. Mealie fails to scrape it, but the problem is strange: in the logs for mealie, it's reporting:

```
10.0.2.100:0 - "POST /api/recipes/test-scrape-url HTTP/1.1" 200
10.0.2.100:0 - "POST /api/recipes/create-url HTTP/1.1" 500
[2022-03-19 13:34:10 -0500] [35] [ERROR] Exception in ASGI application
Traceback (most recent call last):
File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
result = await app(self.scope, self.receive, self.send)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
return await self.app(scope, receive, send)
 ...
    history = [resp for resp in gen]
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

I guess mealie is trying to follow some URL that keeps redirecting, but that URL isn't printed in the logs so can't be investigated.

I have successfully imported recipes from this site, so I don't think they don't provide the necessary metadata; something else is going on.

**Comment by jaspermayone** [comment] 2022-03-20 00:59
Also not picking up on [https://www.thekitchn.com/recipe-20-minute-fresh-tomato-risotto-234113](https://www.thekitchn.com/recipe-20-minute-fresh-tomato-risotto-234113)

**Comment by jaspermayone** [comment] 2022-03-20 01:00
> Mealie doesn't always successfully scrape, but lately I've been seeing something odd. Take this recipe:
> 
> ```
> https://www.eatwell101.com/garlic-butter-chicken-bites-asparagus-recipe
> ```
> 
> There are **no** redirects -- it returns a 200. Mealie fails to scrape it, but the problem is strange: in the logs for mealie, it's reporting:
> 
> ```
> 10.0.2.100:0 - "POST /api/recipes/test-scrape-url HTTP/1.1" 200
> 10.0.2.100:0 - "POST /api/recipes/create-url HTTP/1.1" 500
> [2022-03-19 13:34:10 -0500] [35] [ERROR] Exception in ASGI application
> Traceback (most recent call last):
> File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
> result = await app(self.scope, self.receive, self.send)
> File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
> return await self.app(scope, receive, send)
>  ...
>     history = [resp for resp in gen]
>   File "/opt/pysetup/.venv/lib/python3.9/site-packages/requests/sessions.py", line 677, in <listcomp>
>     history = [resp for resp in gen]
>   File "/opt/pysetup/.venv/lib/python3.9/site-packages/requests/sessions.py", line 166, in resolve_redirects
>     raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
> requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
> ```
> 
> I guess mealie is trying to follow some URL that keeps redirecting, but that URL isn't printed in the logs so can't be investigated.
> 
> I have successfully imported recipes from this site, so I don't think they don't provide the necessary metadata; something else is going on.

That is interesting...

**Comment by jaspermayone** [comment] 2022-03-20 01:01
I wonder if Mealie needs some kind of Adblock and redirect protector?

**Comment by jaspermayone** [comment] 2022-03-20 01:01
@hay-kot what do you think?

(sorry for the ping)

**Comment by hay-kot** [comment] 2022-03-20 01:11
@j-dogcoder 

`https://createplaytravel.com/treats-drinks/freeze-dried-raspberry-macarons/` does not provide micro-data nor is there a scraper implemented in our dependency to manually grab the data. Fortunately, Mealie can also grab meta tags to give you a starter so you should be able to generate something. See here https://demo.mealie.io/recipe/how-to-make-freeze-dried-raspberry-macarons-create-play-travel

@xxxserxxx - Your issue is un-related to this one, but it appears to be resolved in the mealie-next branch. Although, the returned JSON isn't parsed properly since the recipe ingredients is a single string instead of a list. You can create another issue specific to your problem if you'd like, but I suspect an out of date dependency is causing the issue.

**Comment by jaspermayone** [comment] 2022-03-20 14:28
@hay-kot Are there plans for implementing a scraper?

**Comment by hay-kot** [comment] 2022-03-20 16:46
> @hay-kot Are there plans for implementing a scraper?

Not by me. You're welcome to contrubte to the upstream recipe-scrapers project to help them improve the parser or add this site.

**Comment by xxxserxxx** [comment] 2022-03-21 18:20
Thanks, @hay-kot.  I'll make sure I'm up-to-date and see how it goes.

**Closed as completed** 2022-03-28 22:23 UTC
