### ISSUE TITLE
[BUG] - Categories and Tags share query cache In the recipes manager 

### ISSUE THREAD

**Issue by retnag** [mealie-recipes/mealie#3794] opened 2024-06-25 08:04 UTC
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When assigning Tags and Categories to multiple recipes in the data manager, I noticed that the first opened dropdown contents (either categories or Tags) will be shown for both categories and tags.

### Steps to Reproduce

1) click on your user icon in the left menubar
2) select "Manage Data"
3) choose "Recipes"
4) select the first recipe checkmark from the list
5) click on "Actions">"Tag" and look at and remember the Tags list shown when you open the drop-down.
6) click "cancel"
7) click on "Actions">"Categorize" and open the drop-down

### What happens?
The tags list is shown instead of the categories list. The same thing happens if you reverse the order, and open categories first, then the categories are shown when trying to assign tags

### What should happen?
when assigning tags, the up-to-date list of tags should be shown. When assigning categories the up-to-date list of categories should be available to choose from.

### Please provide relevant logs

none

### Mealie Version

confirmed on both `21f1d46b6de06f954895e8dc79451a0676101aa1` and `d96c36333b9cb9461c5dee96ae28b60d912b38fd`

### Deployment

Docker (Linux)

### Additional Deployment Details

deployment via docker

**Comment by michael-genson** [comment] 2024-07-05 19:30
Looks like a duplicate of https://github.com/mealie-recipes/mealie/issues/2200. If this is incorrect, feel free to re-open

**Closed as completed by michael-genson** 2024-07-05 19:30 UTC
Labels: bug, triage

**Comment by retnag** [comment] 2024-07-07 23:14
you are correct. Thank you for pointing it out, I didnt notice it while searching the issues...
