### ISSUE TITLE
[v1.0.0b] - 2021-11-16 -- Other Feedback

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#805] opened 2021-11-16 14:35 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

1) Can't seem to delete a recipe, in the recipe page.  You must either do it from the all recipes page (three buttons), or go into recipe edit (then delete).

2) I think the UI, is a little disorienting to new users on the recipe create page.  Ingredients are full width, but then instructions, and notes are half width.   Regular users get used to it, but we could polish it a little bit.   To me categories and tags should be higher up in the page, as they are important.   Then let Ingredients, instructions, and notes all be full width.   Then put the rest below.   Also I wonder if Recipe name and description need to be full width?  Perhaps make them 80% width, and then you could put total time, prep time, cook time, and servings beside them.
<img width="1420" alt="recipe_create_layout" src="https://user-images.githubusercontent.com/14890934/142005012-19ce157a-ab2f-41a6-ab01-4de10b5f7bff.PNG">

3) I wonder if we need an extra view or filter for Today-Only on the mealplanner.  I'm just thinking about the use case,  getting ready to cook dinner.   Open meal planner on my phone.  Have to scroll down to get to today's recipes.

4) In group/default recipe preferences, I selected 'enable organizing recipe ingredients by units and food'.  It didn't seem to do anything as I created a new recipe.   In the same vein,  i  have show nutrition information in group settings set to false, and it still shows nutrition on recipes.  Allowing comments (in group settings), didn't enable comments on the recipe.

5) In admin settings, when I got to Manage Users.  There is an edit button beside each user.  When I click it.  It shows me a create window.   I can't update/override/enter a new password.

6) If I try to log in with bad credentials on beta.mealie.io/login.   The console log returns 401 status code.  But the login button has an infinite spinner and no indication to the user what is happening.  User can't try  again without reloading the page.

7) On recipe bulk editor (place to add tags and categories).   By default I think user should not be shown.  It doesn't add a ton of value unless you are using mealie in a big group where many people are adding recipes.   If that is not possible, perhaps we can save the column settings.   I can switch user off, but it resets every time i reload the view.

### Deployment

Other

### Deployment Details

Linux,  git-hub clone, and development scripts.  SQLite database.

**Comment by hay-kot** [comment] 2021-11-20 22:24
> Can't seem to delete a recipe, in the recipe page. You must either do it from the all recipes page (three buttons), or go into recipe edit (then delete).

More or less by design. You can delete in the main view (there's still some issues with the DOM updating after deleting) and in the editor. I think that's sufficient. 

> I think the UI, is a little disorienting to new users on the recipe create page. Ingredients are full width, but then instructions, and notes are half width. Regular users get used to it, but we could polish it a little bit. To me categories and tags should be higher up in the page, as they are important. Then let Ingredients, instructions, and notes all be full width. Then put the rest below. 

I disagree with most of this. I think having a single column just shifts things around and potentially out of view. I do agree that maybe the initial view after creation is hard to see what does what. I've added some boilerplate values for new recipes to hopefully clean up the view.

![image](https://user-images.githubusercontent.com/64056131/142742442-c117c4fb-a921-4059-887f-eb60a8f53fde.png)

You now start with an ingredient and some step text so it's a little more clear on what buttons relate to which parts.

> Also I wonder if Recipe name and description need to be full width? Perhaps make them 80% width, and then you could put total time, prep time, cook time, and servings beside them.

Not something I'm going to look at doing. It creates problems on mobile where I'll need to manage state and re-layout items instead of using the auto-scaling that's already in place.

> In group/default recipe preferences, I selected 'enable organizing recipe ingredients by units and food'. It didn't seem to do anything as I created a new recipe. 

This should be fixed in 

- #807 

> In the same vein, i have show nutrition information in group settings set to false, and it still shows nutrition on recipes. Allowing comments (in group settings), didn't enable comments on the recipe.

These two are still WIP

> If I try to log in with bad credentials on beta.mealie.io/login. The console log returns 401 status code. But the login button has an infinite spinner and no indication to the user what is happening. User can't try again without reloading the page.

Fixed in 

- #807

> On recipe bulk editor (place to add tags and categories). By default I think user should not be shown. It doesn't add a ton of value unless you are using mealie in a big group where many people are adding recipes. If that is not possible, perhaps we can save the column settings. I can switch user off, but it resets every time i reload the view.

Fixed in 

- #807

**Closed as completed** 2022-03-17 18:43 UTC
Labels: v1
