### ISSUE TITLE
Import of ZIP files not possible

### ISSUE THREAD

**Issue by FrankSchoene** [mealie-recipes/mealie#2698] opened 2023-10-31 14:28 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Its not possible to import zip-files. Neither for migration nor a single recipe.

### Steps to Reproduce

Wherever you get to the import dialog, you fail. Looks like "submit" is doing just nothing.

### Please provide relevent logs

nothing to log because nothing is happening.

### Mealie Version

**Details**
Version: nightly
Build: 4fc1ec7663f22dd5367c64d1f6009b9abdedac83
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.51.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success

### Deployment

Docker (Synology)

**Comment by brunoelgrande** [comment] 2023-11-04 12:28
Hi
I've got the same problem here.  My collection of recipes comes from **Paprika V2**, so I thought it was the bug (V3 is the most recent and probably the one supported by Mealie ?)

If I refresh the page, I can see that the import is in progress, but nothing change or complete many hours post import. 

![image](https://github.com/mealie-recipes/mealie/assets/90357412/f915f7f2-a2c5-4832-a880-11c74327f0e1)


Nothing in the logs neither. 

**Details**
Version: v1.0.0-RC1.1
Build: 
Mode de l’application: Réalisation
Mode démo: Non
Port de l’API: 9000
Documentation de l’API: Activé
Type de base de données: postgres
Version du Scraper de recette: 14.42.0

**Checks**
Site sécurisé: No
URL de base côté serveur: Yes
Prêt pour LDAP: No
Email Configured: Yes
Docker Volumes: success

**Comment by michael-genson** [comment] 2023-12-11 20:07
Can you guys try upgrading to the latest nightly and see if the behavior persists? We fixed some issues regarding backups and migrations since RC1.1.

Otherwise, can you please post your migration data that's failing? Migrations are working for most folks so your data might contain something we haven't seen previously.

**Comment by brunoelgrande** [comment] 2023-12-12 00:24
> Can you guys try upgrading to the latest nightly and see if the behavior persists? We fixed some issues regarding backups and migrations since RC1.1.
> 
> Otherwise, can you please post your migration data that's failing? Migrations are working for most folks so your data might contain something we haven't seen previously.

Hi, Thanks for the follow-up. 

I got the same error at first, then I tried a smaller number of the recipes zipped in a file.  I've been able to import some.  

Then I thought it was because of the number of recipes in the zipped file, but I've got problem importing a 4 recipes file. 

There's a mix of English and French recipes, so maybe the accents (è,à,é,...) causes problems ?

Here's a zipped file that I can't import (stay on the 'In progress' status) :  

[ExempleRecettes.zip](https://github.com/mealie-recipes/mealie/files/13642215/ExempleRecettes.zip)

Thanks !

---
**Details**
Version: nightly
Build: b1d26283ba425d546780281bc3543800c0d3831e
Mode de l’application: Réalisation
Mode démo: Non
Port de l’API: 9000
Documentation de l’API: Activé
Type de base de données: postgres
Version du Scraper de recette: 14.52.0

**Checks**
Site sécurisé: Oui
URL de base côté serveur: Oui
Prêt pour LDAP: Non
E-mail configuré: Oui

**Comment by boc-the-git** [comment] 2023-12-12 00:27
Pure guess, that I don't have time to follow up on..
Maybe character encoding in postgres?

Does the same file imported against a sqlite dB work?

Are there any logs on the db?

**Comment by brunoelgrande** [comment] 2023-12-12 00:58
> Pure guess, that I don't have time to follow up on.. Maybe character encoding in postgres?
> 
> Are there any logs on the db?

I just try again at 00:54 UTC : nothing shows on the logs of the db 

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-12-11 21:52:33.434 UTC [1] LOG:  starting PostgreSQL 15.5 (Debian 15.5-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2023-12-11 21:52:33.435 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-12-11 21:52:33.435 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-12-11 21:52:33.442 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-12-11 21:52:33.455 UTC [29] LOG:  database system was shut down at 2023-12-11 21:52:21 UTC
2023-12-11 21:52:33.473 UTC [1] LOG:  database system is ready to accept connections
2023-12-11 21:57:33.547 UTC [27] LOG:  checkpoint starting: time
2023-12-11 21:57:38.719 UTC [27] LOG:  checkpoint complete: wrote 54 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=5.140 s, sync=0.017 s, total=5.172 s; sync files=47, longest=0.003 s, average=0.001 s; distance=302 kB, estimate=302 kB
2023-12-11 22:07:33.876 UTC [27] LOG:  checkpoint starting: time
2023-12-11 22:07:34.508 UTC [27] LOG:  checkpoint complete: wrote 7 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.612 s, sync=0.008 s, total=0.633 s; sync files=7, longest=0.005 s, average=0.002 s; distance=3 kB, estimate=272 kB
2023-12-11 22:12:33.587 UTC [27] LOG:  checkpoint starting: time
2023-12-11 22:12:34.217 UTC [27] LOG:  checkpoint complete: wrote 7 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.608 s, sync=0.006 s, total=0.630 s; sync files=7, longest=0.004 s, average=0.001 s; distance=3 kB, estimate=245 kB
2023-12-11 22:22:33.371 UTC [27] LOG:  checkpoint starting: time
2023-12-11 22:22:46.371 UTC [27] LOG:  checkpoint complete: wrote 130 buffers (0.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=12.962 s, sync=0.024 s, total=13.000 s; sync files=84, longest=0.004 s, average=0.001 s; distance=491 kB, estimate=491 kB
2023-12-12 00:12:34.960 UTC [27] LOG:  checkpoint starting: time
2023-12-12 00:12:48.370 UTC [27] LOG:  checkpoint complete: wrote 134 buffers (0.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=13.372 s, sync=0.023 s, total=13.410 s; sync files=79, longest=0.003 s, average=0.001 s; distance=598 kB, estimate=598 kB
2023-12-12 00:17:34.441 UTC [27] LOG:  checkpoint starting: time
2023-12-12 00:17:52.063 UTC [27] LOG:  checkpoint complete: wrote 176 buffers (1.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=17.588 s, sync=0.020 s, total=17.622 s; sync files=79, longest=0.001 s, average=0.001 s; distance=1256 kB, estimate=1256 kB
2023-12-12 00:22:34.130 UTC [27] LOG:  checkpoint starting: time
2023-12-12 00:22:34.960 UTC [27] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.810 s, sync=0.007 s, total=0.831 s; sync files=8, longest=0.004 s, average=0.001 s; distance=22 kB, estimate=1132 kB
```

**Comment by FrankSchoene** [comment] 2023-12-12 09:18
The latest (nightly) container I get on my Synology is from 29th October. So I can't test a newer version.

**Comment by michael-genson** [comment] 2023-12-12 14:07
Are you using the new container manager? Container manager supports docker compose (called projects) which will let you use the newest version.

If you can't upgrade your DSM to get the container manager, you can enable SSH and use docker compose that way

**Comment by FrankSchoene** [comment] 2023-12-12 21:18
I have container manager but it does not accept to change the registry to ghcr.io (ends up with an error). Anyhow, doing it via CLI or Portainer works.

I've set up the nightly build from scratch but I still can't import from the PreV1 version. When trying to import a single recipe I end up with "In-Progress" forever; when trying an import of the whole database (all recipes from the old container) I just get nothing back from the system (frontend).

There is nothing in the logs apart from info about the installation.

**Comment by michael-genson** [comment] 2023-12-12 21:23
Can you post your backup?

Weird that ghcr isn't working, that's how I have mine set up through container manager

**Comment by FrankSchoene** [comment] 2023-12-12 21:40
Take this please 
[Mealie.zip](https://github.com/mealie-recipes/mealie/files/13653440/Mealie.zip)

**Comment by michael-genson** [comment] 2023-12-12 21:49
I just tried it and it works fine on my instance. Are you setting the migration to Mealie?

![image](https://github.com/mealie-recipes/mealie/assets/71845777/5ce67de6-0f2e-4ff4-a446-0892f2974b10)

**Comment by FrankSchoene** [comment] 2023-12-12 21:55
Yes I do.
![Bildschirmfoto vom 2023-12-12 22-53-35](https://github.com/mealie-recipes/mealie/assets/83726061/15893f51-c133-42a1-963e-ba884e8ad65a)

**Comment by michael-genson** [comment] 2023-12-12 22:01
@brunoelgrande the culprit seems to be your Biscuits bleuets et citron recipe - it has no instructions or ingredients, and the parsing is failing. If you remove that recipe the import should work.

That's a bug though, we should be handling that, I'll open a PR to fix it

**Comment by michael-genson** [comment] 2023-12-12 22:02
@FrankSchoene can you confirm you're on the latest nightly? Can you share your deployment details? I can't reproduce on nightly

**Comment by FrankSchoene** [comment] 2023-12-12 22:10
This is the stack on Portainer I've used. Password etc. changed. I don`t think that I get anything else tha the latest nightly.

![Bildschirmfoto vom 2023-12-12 23-10-25](https://github.com/mealie-recipes/mealie/assets/83726061/aaa1f2e3-d4ad-492e-8784-13b2b432f158)


`version: "3.9"
services:
  db:
    image: postgres
    container_name: Mealie-DB
    hostname: mealie-db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "mealie", "-U", "mealieuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume2/docker/mealiev1/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: mealie
      POSTGRES_USER: mealieuser
      POSTGRES_PASSWORD: mealiepass
    restart: on-failure:5

  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
    container_name: Mealie
    hostname: mealie
    mem_limit: 3g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    ports:
      - 9925:9000
    volumes:
      - /volume2/docker/mealiev1/data:/app/data/:rw
    environment:
      TZ: Europe/Vienna
      PUID: 1026
      PGID: 100
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      ALLOW_SIGNUP: true #or false
      BASE_URL: http://mydockerip #or https://mealie.yourname.synology.me
      DB_ENGINE: postgres
      POSTGRES_USER: mealieuser
      POSTGRES_PASSWORD: mealiepass
      POSTGRES_SERVER: mealie-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
      SMTP_HOST: mysmtphost
      SMTP_PORT: 587
      SMTP_FROM_NAME: Mealie
      SMTP_AUTH_STRATEGY: NONE # Options: 'TLS', 'SSL', 'NONE'
      SMTP_FROM_EMAIL: myemail
      SMTP_USER: mysmtp
      SMTP_PASSWORD: mypw
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy`

**Comment by michael-genson** [comment] 2023-12-12 22:19
That's the build I'm on and I'm not seeing any issues with it using your .zip file. I spun up a fresh db just to be safe, and I'm able to successfully import your data:

![2023-12-12_16h18_30](https://github.com/mealie-recipes/mealie/assets/71845777/4fc24a0b-0e8c-40d5-84ef-f21c20ccd117)

**Comment by michael-genson** [comment] 2023-12-12 22:19
Is it possible your network is blocking uploads?

**Comment by FrankSchoene** [comment] 2023-12-12 22:33
I don't think so -- even though it looks like. I'm about to define firewall rules but until now its paperwork :-) It's plain Synology (alsmost out of the box) and docker at this part of the network.

**Comment by brunoelgrande** [comment] 2023-12-12 23:00
> @brunoelgrande the culprit seems to be your Biscuits bleuets et citron recipe - it has no instructions or ingredients, and the parsing is failing. If you remove that recipe the import should work.
> 
> That's a bug though, we should be handling that, I'll open a PR to fix it

Good catch !  I've got 5 recipes that were just photos or with no ingredients.  They were the one causing problems. 

An error message such as : `Impossible to import Biscuits bleuets et citron` in the import tool would be helpful for these cases.

Thanks so much 👍🏼

**Comment by FrankSchoene** [comment] 2023-12-12 23:01
And just in case, I just tried incognito mode, disabled ad-blocker, tried another browser, tried another app (container) on docker with uploads (works) ... I guess for today I have no more ideas .... At least you have now some nice recipes :-) Try the "Schwäbische Brezeln"

**Comment by FrankSchoene** [comment] 2024-01-06 13:27
I did a fresh install; this time with sqlite rather then postgress; now its working. Should I close the issue or leave it open since others seem to have the same trouble.

**Comment by brunoelgrande** [comment] 2024-01-06 15:05
> I did a fresh install; this time with sqlite rather then postgress; now its working. Should I close the issue or leave it open since others seem to have the same trouble.

@FrankSchoene It's good for me. Thank you

**Comment by Kuchenpirat** [comment] 2024-01-06 15:17
Great that is sorted itself out 👍
As long as it is not possible for us to reproduce the issue we cannot confirm and fix it. 

I'll close this for now, but feel free to reopen if the problem arrises again.

**Closed as completed by Kuchenpirat** 2024-01-06 15:17 UTC
Labels: bug, triage
