### ISSUE TITLE
[BUG] - Shopping list - label for food only appears after saving the entry

### ISSUE THREAD

**Issue by xlemassacre** [mealie-recipes/mealie#2910] opened 2024-01-05 23:53 UTC
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When adding food into the shopping list, the label is not immediately displayed after selecting the food from the dropdown

### Steps to Reproduce

1)  in data management create a label
2) in data management create a food an assign the label to the food
3) create a new shopping list
4) in the new shopping list add a new item with button create
5) click on the "apple" button to allow food selection
6) select the food created in step 2

the label is not displayed after selecting the food

7) save the item

the label is now displayed

### Please provide relevant logs

can't find relevant logs
 POST /api/groups/shopping/items HTTP/1.1" 201 Created

### Mealie Version

todays nightly build

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment] 2024-02-05 04:40
I can't reproduce this one anymore, it may have been fixed by https://github.com/mealie-recipes/mealie/pull/3056. If you're still seeing this on the latest nightly, feel free to re-open

**Comment by xlemassacre** [comment] 2024-02-15 18:26
I have tried it now with v1.2.0 but i still have the same issue. After selecting the food, the label is empty and only after saving it is displayed

**Comment by michael-genson** [comment] 2024-02-15 21:08
Ah I see it now, I wasn't looking in the right place before. I opened a PR for it, should be fixed in the next version once that gets merged

**Comment by xlemassacre** [comment] 2024-02-17 13:58
Thanks for reopening it and having another look, great to hear you were able to fix it.

**Closed as completed** 2024-02-18 19:59 UTC
Labels: bug, triage
