### ISSUE TITLE
[v1.0.0b] PWA shows white-screen when logged in (sometimes)

### ISSUE THREAD

**Issue by 14wkinnersley** [mealie-recipes/mealie#1077] opened 2022-03-21 04:44 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

After setting up Mealie 1.0.0b, I added a homescreen shortcut within iOS, and initially it worked, it let me login. After closing out, and closing out from the iOS “task manager”, It will no longer load correctly. I see the login screen for a brief moment, and then it goes to a white page. This only occurs for the iOS Add to Homescreen function. 

### Deployment

Docker (Linux)

### Deployment Details

I run this within docker on Ubuntu Server 20.04 Headless. I run the site behind Nginx Proxy Manager.

**Comment by hay-kot** [comment] 2022-03-21 04:49
I noticed this today as well on Android, seems intermittent for me. Will dig into it this week.

**Comment by hay-kot** [comment] 2022-03-23 03:53
<s> Okay, so I was able to replicate this pretty easily on iOS, Android, and MacOS. I'm thinking it has something to do with SSR but I'm pretty stumped on what's causing the issue. 

Hoping someone else might have an idea of what's going on.

As a temporary work around, if you can tap login fast enough it will let you pass the login screen, which I know is not ideal 😞 

</s>

Edit: I'm an idiot and used fetch on the server. See here

- https://github.com/hay-kot/mealie/pull/1086/commits/b10ce50f7261ccdacf0876cf2d36e96a188f8cc3

_Should_ be fixed when that PR is merged

**Comment by zierbeek** [comment] 2022-03-23 11:25
thinks this is still happening?

**Comment by hay-kot** [comment] 2022-03-23 15:07
> thinks this is still happening? 

I haven't been able to replicate it with the most recent build. Make sure you grab the latest build of the nightly containers. You might also need to reinstall the PWA.

**Comment by 14wkinnersley** [comment] 2022-03-23 15:23
I did some testing:

It works ✅ if I add the PWA homescreen icon for the direct local IP Address to Mealie. 

It does not ❌ work if mealie is behind a reverse proxy (NGINX Proxy Manager in my case) ie: accessing mealie from https://mealie.domain.com

**Comment by 14wkinnersley** [comment] 2022-03-23 15:29
> > thinks this is still happening? 
> 
> I haven't been able to replicate it with the most recent build. Make sure you grab the latest build of the nightly containers. You might also need to reinstall the PWA. 

I did some testing:

It works ✅ if I add the PWA homescreen icon for the direct local IP Address to Mealie.

It does not ❌ work if mealie is behind a reverse proxy (NGINX Proxy Manager in my case) ie: accessing mealie from https://mealie.domain.com

**Comment by zierbeek** [comment] 2022-03-23 15:49
issues are indeed gone after a removal :) both on Nginx and local :)

**Comment by 14wkinnersley** [comment] 2022-03-23 15:54
> issues are indeed gone after a removal :) both on Nginx and local :) 

Hmm ill do some more testing. It only works the first time behind NGINX for me. After I close out the PWA from the "task manager" it no longer works, and I get the same issues as before. I did try setting it up on a whole new subdomain and it still did not work. Do you use NGINX Proxy Manager?

**Comment by zierbeek** [comment] 2022-03-23 15:56
Ah yeah indeed, after force closing it, issues return! Using SWAG

________________________________
Van: Wells ***@***.***>
Verzonden: woensdag 23 maart 2022 16:54
Aan: hay-kot/mealie ***@***.***>
CC: zierbeek ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [hay-kot/mealie] [v1.0.0b] PWA shows white-screen when logged in (sometimes) (Issue #1077)


issues are indeed gone after a removal :) both on Nginx and local :)

Hmm ill do some more testing. It only works the first time behind NGINX for me. After I close out the PWA from the "task manager" it no longer works, and I get the same issues as before. I did try setting it up on a whole new subdomain and it still did not work. Do you use NGINX Proxy Manager?

**Comment by hay-kot** [comment] 2022-03-23 16:07
<s> Does this issues also occur on the Beta sites PWA? 

https://beta.mealie.io/

</s> 

Never-mind, I got it to fail. Back to the drawing board.

**Comment by 14wkinnersley** [comment] 2022-03-23 16:09
> <s> Does this issues also occur on the Beta sites PWA? 
> 
> 
> 
> https://beta.mealie.io/
> 
> 
> 
> </s> 
> 
> 
> 
> Never-mind, I got it to fail. Back to the drawing board. 

Just tested, no issues with the demo site.

**Comment by hay-kot** [comment] 2022-03-23 16:15
Yeah, this is thoroughly confusing. I think the PR I did resolved the core issue that was causing the error, but the PWA is doing some aggressive caching that is causing the pages not to render correctly. 

It may be that you need to uninstall the PWA and delete all associated page data and re-install the PWA to get this to be resolved? I've done that and so far so good on my Ipad and Android phone and MacBook 🤞

**Comment by 14wkinnersley** [comment] 2022-03-23 16:23
> Yeah, this is thoroughly confusing. I think the PR I did resolved the core issue that was causing the error, but the PWA is doing some aggressive caching that is causing the pages not to render correctly. 
> 
> 
> 
> It may be that you need to uninstall the PWA and delete all associated page data and re-install the PWA to get this to be resolved? I've done that and so far so good on my Ipad and Android phone and MacBook 🤞

No dice for me. I removed all PWA for it, and even setup access on a whole other domain, created the new PWA, and had the same issue. Ill keep doing some testing on my end with the reverse proxy and see if I can get anywhere.

**Comment by hay-kot** [comment] 2022-03-23 16:31
Bummer, I'd double check that you've got the latest build `docker-compose pull && docker-compose up -d` just in case.

**Comment by hay-kot** [comment] 2022-03-27 21:31
Checking in on this again. I haven't had the issue since updating and have been using it pretty regularly.

**Comment by 14wkinnersley** [comment] 2022-03-27 23:34
> Checking in on this again. I haven't had the issue since updating and have been using it pretty regularly. 

I still have the issue on the latest update. Tried deleting and reinstalling the PWA. Just tried a few minutes ago. No help. Gave up on using it

**Comment by tbleiker** [comment] 2022-03-28 10:50
Same here
- Android 12 (Pixel 4a)
- Docker (Linux), current nightlies, behind proxy (traefik)

**Comment by CarloDePieri** [comment] 2022-04-08 10:57
My 2c about this:
- as of today, the PWA is not working correctly on my android 11 device (pixel 2xl) and android 12 device (pixel 4a)

My setup is nightlies docker, behind traefik; this stack went up yesterday for the first time on this server so images are up-to-date.
On both device I also completely cleared the website data from the browsers (tried chrome, chrome-beta, firefox, kiwi) when reinstalling the pwa.

Thank you for all your work on this project!

**Comment by hay-kot** [comment] 2022-04-09 18:34
Not much I can do on this to troubleshoot since I can't replicate the issue with any of my devices. If anyone can troubleshoot on their end with a remote debugger with chrome or eq. and can provide some more information or ideas on what causing the issue that would be really helpful.

**Comment by 14wkinnersley** [comment] 2022-04-10 03:02
> Not much I can do on this to troubleshoot since I can't replicate the issue with any of my devices. If anyone can troubleshoot on their end with a remote debugger with chrome or eq. and can provide some more information or ideas on what causing the issue that would be really helpful. 

I just tested this using even Microsoft Edge in Windows 11 by adding the "application" to my desktop and had the same issue. I can run debugger tools if needed but I dont really know what im doing with all that. I could create a dummy user account maybe for you to test if you need?

**Comment by CarloDePieri** [comment] 2022-04-10 07:59
> Not much I can do on this to troubleshoot since I can't replicate the issue with any of my devices. If anyone can troubleshoot on their end with a remote debugger with chrome or eq. and can provide some more information or ideas on what causing the issue that would be really helpful.

I can reproduce this behavior even on chrome (Version 99.0.4844.84 (Official Build) (64-bit)) on my linux machine (the build number of Mealie as reported in Settings -> General about -> Build is 10784b6e242b941b76ce21186c4279bcd4037789 by the way).

**How to reproduce on chrome on pc**
- Uninstall any previously installed pwa version
- Clear all website data by clicking on 'clear site data' in the Application -> Storage tab of the Developer Tools (Menu -> more tools -> Developer Tools)
- Install the pwa by pressing the button in the address bar or Menu -> Install Mealie...
- In the newly installed pwa, log in. Everything should work correctly
- Close the application
- Open the pwa again by going to chrome://apps, apps tab (or by launching it by the shortcut created by your os)
- The login menu flashes for a second, then a blank white screen appears.

All http request succeeded, but the console report an error:

```
7b44a51.js:2 TypeError: Cannot read properties of undefined (reading '_isDestroyed')
    at destroy (7b44a51.js:2:21512)
    at E (7b44a51.js:2:55951)
    at E (7b44a51.js:2:56050)
    at E (7b44a51.js:2:56050)
    at f.__patch__ (7b44a51.js:2:59472)
    at f.t.$destroy (7b44a51.js:2:36269)
    at destroy (7b44a51.js:2:21555)
    at E (7b44a51.js:2:55951)
    at f.__patch__ (7b44a51.js:2:59472)
    at f.t.$destroy (7b44a51.js:2:36269)
```

The js is mimified so it's not easly debugged: maybe later I'll manage to setup Mealie in dev mode and look further into this issue.

**Comment by CarloDePieri** [comment] 2022-06-09 11:30
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

Good bot.

The issue is still relevant though!
I just reproduced it with a fresh nightly (beta3) installation following the step I outlined above.

**Comment by hay-kot** [comment] 2022-06-09 15:51
Marked it as confirmed, issue should stick around now.

**Comment by zierbeek** [comment] 2022-08-03 06:07
Possible fix is uploaded. Could all of you give it a try? Maybe feinstalling thé pwa

**Comment by tbleiker** [comment] 2022-08-03 06:50
It seems to work now. Thx!

**Comment by VS-X** [comment] 2022-08-03 11:18
Can confirm, @zierbeek's fix seems to work. I `exec`'d into the running frontend container, changed the `static/manifest.json` file, ran `yarn build` and restarted the container. Re-added PWA and it works fine. Thanks!

**Comment by 14wkinnersley** [comment] 2022-08-03 12:51
Does work by going to the localip and setting PWA so that is good news! Does not work behind Cloudflare tunnel reverse proxy. Ill do some T/S later and try to remove the tunnel and dns altogether and see if a fresh setup will work.

**Comment by zierbeek** [comment] 2022-08-03 12:52
for me, it works behind swag reverse proxy. Have you pulled the nightly?

**Comment by dronf** [comment] 2022-08-03 17:24
Working for me on android PWA. For reference, the instance is behind Nginx Proxy Manager.

**Comment by 14wkinnersley** [comment] 2022-08-03 19:21
> Working for me on android PWA. For reference, the instance is behind Nginx Proxy Manager.

Did you have to do anything specific in NPM? I moved mine behind NPM and still no dice.

**Comment by hay-kot** [comment] 2022-08-03 19:28
Wanted to clarify that this fix is only available in the nightly release. 

You'll also probably have to uninstall the PWA and maybe nuke the cache. Sometimes those manifest can be a bugger to get removed.

**Comment by 14wkinnersley** [comment] 2022-08-03 19:55
> Wanted to clarify that this fix is only available in the nightly release. 
> 
> You'll also probably have to uninstall the PWA and maybe nuke the cache. Sometimes those manifest can be a bugger to get removed. 

Confirmed I am on the nightly image, and PWA/device cache has been removed. Is there any cache within mealie that I would need to clear? On iOS just FYI, right now its behind Nginx Proxy Manager. I will also try setting up mealie on a whole new server from scratch later and see if I can make any progress.

**Comment by dronf** [comment] 2022-08-03 19:57
> > Working for me on android PWA. For reference, the instance is behind Nginx Proxy Manager.
> 
> Did you have to do anything specific in NPM? I moved mine behind NPM and still no dice.

I didn't change anything in NPM.  It was working before in 0.5.3, then failed in the release 1.0.0b4.  You DO need to delete the PWA on your home screen and create a new one.  The one I had before the update continued to give the white screen after the update, but a fresh one worked fine(and was even logged in).

**Comment by 14wkinnersley** [comment] 2022-08-03 20:23
At this point I am not sure what is wrong. Setup mealie on a whole new fresh VM. Behind NPM. Only differences I may have, is running from iOS, and my dns provider is Cloudflare which mealie is not setup through their proxy. Wonder if Cloudflare is causing the issues and could be changing anything somehow. Would like to see if anyone else runs their setup through Cloudflare. Tried from 3 different iOS devices. I do not have an android to test.

**Comment by hay-kot** [comment] 2022-08-03 20:25
> At this point I am not sure what is wrong. Setup mealie on a whole new fresh VM. Behind NPM. Only differences I may have, is running from iOS, and my dns provider is Cloudflare which mealie is not setup through their proxy. Wonder if Cloudflare is causing the issues and could be changing anything somehow. Would like to see if anyone else runs their setup through Cloudflare. Tried from 3 different iOS devices. I do not have an android to test.

Is CloudFlair doing any kind of cacheing? If it doesn't fetch the new manifest file, it wont apply the update. If CloudFlair is caching the old manifest file that would keep the change from coming through to your end device.

**Comment by 14wkinnersley** [comment] 2022-08-03 20:48
I disabled and purged all cache. Added a Cloudflare rule to bypass cache, still no luck.

**Comment by FrouxBY** [comment] 2022-08-03 22:11
I have tried quickly, it was not working  on my side

My test was updating the image, and installing the WPA on an Android phone after wiping all cache on it

I need to do more test on other platform (iOS, windows-Chromium),
And restart my forward proxy (Traefik) to be sure
I'll keep you informed on those other trials,

Best

**Comment by 14wkinnersley** [comment] 2022-08-03 23:39
> Can confirm, @zierbeek's fix seems to work. I `exec`'d into the running frontend container, changed the `static/manifest.json` file, ran `yarn build` and restarted the container. Re-added PWA and it works fine. Thanks!

Where did you have to run _yarn build_ at? Trying to manually change my setting for testing.

**Comment by VS-X** [comment] 2022-08-04 07:31
> Where did you have to run _yarn build_ at?

In the `/app`, the working directory of the container. Forgot to mention that you may also have to run `yarn install` before `yarn build`

**Comment by VS-X** [comment] 2022-08-04 14:48
Update: just tested on an iPhone (previous test was using Android), and there the issue still happens.
What I also noticed is that I can't logout on the Android - I logout, close the PWA, open it again and it loads directly into the app, without any login screens. Not sure if related.

**Comment by zierbeek** [comment] 2022-08-04 14:53
> Update: just tested on an iPhone (previous test was using Android), and there the issue still happens.
> What I also noticed is that I can't logout on the Android - I logout, close the PWA, open it again and it loads directly into the app, without any login screens. Not sure if related.

Can confirm the logout behavior

**Comment by zierbeek** [comment] 2022-08-04 14:56
@hay-kot could you check if there is a route to '/' ? 
https://forum.vuejs.org/t/blank-screen-after-pwa-update-on-ios/72504/6 

also read about this : 
https://forum.vuejs.org/t/blank-screen-after-pwa-update-on-ios/72504/3
known issue on iOS https://github.com/PWA-POLICE/pwa-bugs#problem-navigation-to-a-website-has-infinite-loading

**Comment by zierbeek** [comment] 2022-08-04 18:44
Let's hope that that fixed it for ios users

**Comment by hay-kot** [comment] 2022-08-04 18:47
Just merged a possible fix from @zierbeek (Thanks!). If you're still experiencing the issues, please try to latest nightly build once it's finished building.

Additionally, if you're still experiencing the issue please provide the following details

- Phone Type Android / IPhone / Other and Version
- Browser being used
- Mealie Git Commit Hash (from your settings page) 
- What proxy you're using and if you're using CloudFlair.

**Comment by FrouxBY** [comment] 2022-08-04 21:23
I have tried again with the latest build (505e594758038b36caba7510f8321e8555ff05ff on settings pages)
No Luck on my side on any of those 3 devices: 
Safari on  iPad Pro iOS 15
Chrome on Android 11 (Samsung) 
Vivaldi (chromium) on Windows 10

On Windows 10, if I hard refresh, or delete cookies, It works again, and I can get the following error in the JS console 

> TypeError: Cannot read properties of undefined (reading '_isDestroyed')
    at destroy (63b08e6.js:2:21513)
    at E (63b08e6.js:2:55952)
    at E (63b08e6.js:2:56051)
    at E (63b08e6.js:2:56051)
    at f.__patch__ (63b08e6.js:2:59473)
    at f.t.$destroy (63b08e6.js:2:36270)
    at destroy (63b08e6.js:2:21556)
    at E (63b08e6.js:2:55952)
    at f.__patch__ (63b08e6.js:2:59473)
    at f.t.$destroy (63b08e6.js:2:36270)
re @ 63b08e6.js:2

which does not appear one the browser, only when the PWA is installed and when I get the blank page,

Edit: I use Traefik 2.8 as a reverse proxy, without any caching involved I think

Hope this can help

**Comment by 14wkinnersley** [comment] 2022-08-04 21:59
Issue is persisting. 
iOS 15.6 on two separate iphones. iOS 16 Beta on one iphone. 
Safari browser. 

Build
505e594758038b36caba7510f8321e8555ff05ff

Reverse proxy: Nginx Proxy Manager
DNS: Cloudflare

**Comment by epheterson** [comment] 2022-08-08 22:08
This is still happening for me too, same config as above.

iPhone / iOS 16
`56eb0bca7142715984c8028c4c881f086e979564`
Synology DSM reverse proxy, I believe it's Nginx underneath
DNS: Cloudflare

Edit: Actually it was doing this the last couple days, but just tried today and seems to be resolved! Thanks!

Edit 2: It is still failing on my wife's iPad running iOS 15.6

**Comment by m10x** [comment] 2022-08-27 09:37
Android 12 & 13
Build 13850cda1f9cb02a8c788030ba6cfa96bba33571
Browsers used: Vanadium, Firefox, Brave
Proxy: Traefik / Caddy (happens with both)

https://mealie.mydomain.de/?standalone=true shows shortly (half second) the mealie login page (w/o darkmode), then white blank screen. When i press fast enough on a button (e.g. login or reset password) I'm logged in and can use mealie as normal.
when using https://mealie.mydomain.de/?standalone=false, mealie behaves totally normal. I'm logged in and it uses the darkmode as specified

Using the internal ip (both with standalone true or false), mealie behaves normal, too.

So to circumvent this bug, I refresh the pwa and try to spam a button. If I'm fast enough and press a button during the half second they are shown, I can use it as normal

**Comment by HoroTW** [comment] 2022-09-17 00:09
Hey hey,
found this bug too and can easily recreate it on the desktop too (PWA on Desktop Chromium).
To recreate I just create a PWA and then I can trigger it by logging in and then refreshing the pwa with F5 - a `invalidate cache and refresh` (ctrl+F5) brings the PWA back - with F5 its back to white again and so on....

So the fix https://github.com/hay-kot/mealie/pull/1526 did sadly not reslove it. (I used the current nightly to test it)

As @m10x said it has to do with the `standalone=true` which is the default `start_url` for pwa sites in nuxt....

As I don't have that much web developer knowledge I think the following could be helpful: 
 - https://github.com/nuxt-community/pwa-module/issues/381
 - https://github.com/nuxt-community/pwa-module/issues/406

Maybe it has todo with my setup - I run the beta 4 in docker with compose **behind a second caddy as reverse proxy.**
If I go directly to the mealie frontend the bug is gone.... but yeah not really a solution - It feels like the second caddy instance triggers ssr and caching at the same time or something like that :see_no_evil: (again not a web dev guy)

@hay-kot What is the setup on the Demo Server?

**Comment by Bottleface** [comment] 2022-10-26 05:39
Can confirm that this issue still exists on beta5.  I can reproduce easily on 2 Android phones, a chromebook, and windows.  The site works fine if I remove the standalone=true query string, or set it to false.  Issue is that you can't really do that with a PWA.

I am running mealie in docker with the reverse proxy built into synology's NAS devices.  As far as I can tell everything is working perfectly minus this bug.

**Comment by Opethel** [comment] 2023-01-02 01:09
Also experiencing this issue on v1.0.0beta-5, IOS16.

**Comment by hay-kot** [comment] 2023-01-04 02:36
I was able to reproduce the issue and the fix in #1982 _did_ resolve it on my laptop's PWA. If you can, once the build is finished - try the latest nightly and let me know if this issue is still present.

**Comment by 14wkinnersley** [comment] 2023-01-04 03:54
> I was able to reproduce the issue and the fix in #1982 _did_ resolve it on my laptop's PWA. If you can, once the build is finished - try the latest nightly and let me know if this issue is still present. 
> 
> 
> 
> 

I only saw API-Nightly update, and can confirm the issue persists after upgrading, clearing caches, and trying across multiple iOS devices and windows 11.

**Comment by michael-genson** [comment] 2023-01-04 05:03
> I only saw API-Nightly update, and can confirm the issue persists after upgrading, clearing caches, and trying across multiple iOS devices and windows 11.

It's still building, it usually takes 2-3 hours
https://github.com/hay-kot/mealie/actions/runs/3834700359

**Comment by hay-kot** [comment] 2023-01-04 15:40
I'm got some confirmations on discord that this issue is resolved on the latest nightly image.

To use the fix, be sure to

1. Delete your current PWA installation
2. Clear cookies and storage for the website.

After that things _should_ work as expected. Please report back good or bad results!

**Comment by michael-genson** [comment] 2023-01-04 16:21
Doesn't seem to be working for me. It looks like it's correctly logging me back in (I don't have to login twice) but the redirect from the login screen isn't working (it goes to a white screen).

On the site in mobile I can manually go to another page (e.g. all recipes) and it loads fine (and I'm logged-in) but the initial state in the app fails to redirect to the home page.

I tried killing site data and cookies in like 5 different ways (thanks Android) but similar results for all of them. Also the app name is "mealie" with a lowercase m now, weirdly

**Comment by 14wkinnersley** [comment] 2023-01-04 16:23
> I'm got some confirmations on discord that this issue is resolved on the latest nightly image.
> 
> To use the fix, be sure to
> 
> 1. Delete your current PWA installation
> 2. Clear cookies and storage for the website.
> 
> After that things _should_ work as expected. Please report back good or bad results! 

On the latest build, issue is still occurring for me. Steps taken: 

iPhone 14: Cleared cache and website data, tested on wifi. cleared cache and data again, tested on cellular. Issue persisted.

iPhone 12: Cleared cache and website data, tested on wifi. cleared cache and data again, tested on cellular. Issue persisted.

Cloudflare: Purged all cache

Nginx proxy manager: removed, then re-added the configuration for mealie, issue persisted. Then removed it entirely, set up a reverse proxy with Cloudflare tunnel, issue persisted.

Windows 11: Issue resolved. 

Seems like the issue may still be impacting Apple iOS devices.

**Comment by hay-kot** [comment] 2023-01-04 20:33
I'm getting a similar, but slight different issue now. I think I've solved the auth issue that was part of the problem. The problem I'm seeing now is the redirect is broken, and never mounts the home page. If you navigate to another page the site seemingly works fine. 

Will take another crack resolving that issue and report back!

**Comment by michael-genson** [comment] 2023-01-04 23:23
> I'm getting a similar, but slight different issue now. I think I've solved the auth issue that was part of the problem. The problem I'm seeing now is the redirect is broken, and never mounts the home page. If you navigate to another page the site seemingly works fine.

FWIW I'm seeing it on desktop now, too. Easy workaround is to just go directly to any other page, for now.

**Comment by hay-kot** [comment] 2023-01-05 06:13
Okay this build might fix it!

- https://github.com/hay-kot/mealie/actions/runs/3843774919

But who knows at this point 🤷

**Comment by 14wkinnersley** [comment] 2023-01-05 13:24
> Okay this build might fix it!
> 
> - https://github.com/hay-kot/mealie/actions/runs/3843774919
> 
> But who knows at this point 🤷

@hay-kot I can now confirm, the issue is resolved for me! Tested on iOS. Thank you so much for all the hard work that went into fixing this! 😀

**Comment by michael-genson** [comment] 2023-01-05 14:30
This fixed it on my phone's browser, but the PWA still doesn't redirect properly (white screen).
But if I go to my browser and hit "open in Mealie" it brings me to the recent recipes page, which works...

The fact that I'm getting different behavior is strange, so maybe my phone is caching something (despite nuking my cache)

**Comment by hay-kot** [comment] 2023-01-05 15:22
> This fixed it on my phone's browser, but the PWA still doesn't redirect properly (white screen).
> But if I go to my browser and hit "open in Mealie" it brings me to the recent recipes page, which works...
> 
> The fact that I'm getting different behavior is strange, so maybe my phone is caching something (despite nuking my cache)

Are you deleting the PWA and reinstalling it? I believe you have to do that to get the new manifest.

**Comment by michael-genson** [comment] 2023-01-05 15:35
Yeah, I tried uninstalling the app, clearing all data in Chrome, clearing all of Chrome's app data, no dice.
Conveniently, if I do the workaround once (open in Chrome, then choose "open in mealie") it keeps me in the right place when I re-open the app (no white screen). However if I close the app and re-open it, or hit back a few too many times, the redirect doesn't work properly (white screen).

Interestingly, if I open the PWA first, get the white screen, then choose "open in Chrome" the white screen persists in Chrome, indicating it's not strictly a PWA issue. But I have no way of reproducing this using only the browser, I have to cause the issue in the PWA first.

**Comment by 14wkinnersley** [comment] 2023-01-05 18:56
I may have spoke too soon. I am also getting the white screen. I attempted to set the PWA on another device, and after logging in, closing the PWA completely, then reopening; the white screen shows. 

For the device that it worked on initially, I noticed when I first added to homescreen this morning and it worked, it had only the base URL. Now when going to add mealie to homescreen it has /?standalone=true appended at the end of the base url.

**Comment by articuno1au** [comment] 2023-01-06 05:24
Just cross-linking. I started encountering this issue after installing the attempted fix for #1816. I've completely blown away the storage for the site and all cookies, but the issue persists.

I wasn't previously encountering the problem, so this is a new behaviour. Let me know if there's any testing I can perform for you.

I've got my configuration listed in https://github.com/hay-kot/mealie/issues/1816#issue-1446750910

**Comment by hay-kot** [comment] 2023-01-06 19:26
@articuno1au, do you know the last good build number where you weren't experiencing the PWA error?

**Comment by michael-genson** [comment] 2023-01-06 19:36
FWIW I wasn't experiencing it before either, but that's because it logged me out every time I opened the PWA, so I never had the chance for the redirect to fail (because it never redirected).

So the issue still existed, it just basically got cancelled out by the login state not persisting

**Comment by hay-kot** [comment] 2023-01-06 19:54
Trying another fix 

- https://github.com/hay-kot/mealie/actions/runs/3858063510

Will give it a try again once the build is complete. 🤞

**Comment by 14wkinnersley** [comment] 2023-01-07 01:00
> Trying another fix 
> 
> 
> 
> - https://github.com/hay-kot/mealie/actions/runs/3858063510
> 
> 
> 
> Will give it a try again once the build is complete. 🤞

Tested and confirmed its operational for me across multiple devices! Thanks so much!!

**Comment by articuno1au** [comment] 2023-01-07 01:08
![image](https://user-images.githubusercontent.com/18381114/211124181-20c6608c-73ff-4642-8aec-f92af9f34f8f.png)
---
EDIT::
Actually, I can't confirm this is fixed on my end. I'm getting a JSON dump appearing in the PWA window when opening it
```
{
  "name": "Mealie",
  "short_name": "mealie",
  "icons": [
    {
      "src": "/_nuxt/icons/icon_64x64.af4555.png",
      "sizes": "64x64",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_120x120.af4555.png",
      "sizes": "120x120",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_144x144.af4555.png",
      "sizes": "144x144",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_152x152.af4555.png",
      "sizes": "152x152",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_192x192.af4555.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_384x384.af4555.png",
      "sizes": "384x384",
      "type": "image/png",
      "purpose": "any maskable"
    },
    {
      "src": "/_nuxt/icons/icon_512x512.af4555.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "any maskable"
    }
  ],
  "start_url": "",
  "display": "standalone",
  "background_color": "#FFFFFF",
  "theme_color": "#E58325",
  "lang": "en",
  "title": "Mealie",
  "share_target": {
    "action": "/",
    "method": "GET",
    "params": {
      "title": "title",
      "text": "recipe_import_url"
    }
  }
}
```

I've cleared all the data, and same result. I've also confirmed I'm on the latest nightly docker container (might not have made it to Docker yet?).

**Comment by hay-kot** [comment] 2023-01-07 02:05
> Actually, I can't confirm this is fixed on my end. I'm getting a JSON dump appearing in the PWA window when opening it

I was getting the same earlier today. Trying another fix, should be built soon.

https://github.com/hay-kot/mealie/actions/runs/3859534260

**Comment by michael-genson** [comment] 2023-01-07 04:23
Latest one seems to work correctly!

**Comment by hay-kot** [comment] 2023-01-07 04:32
Looks to be working for me as well!

**Comment by articuno1au** [comment] 2023-01-07 06:10
So, it's not working for me, but I'm unsure if I have the correct code.

I'm currently running the following front-end hash: sha256:400eb63197207faa11d1370f29abbf237dbf9b35628a0306cd85dabdd767b56c
back-end hash:
sha256:98fe68351473c00b596117fdd20e344dad8a1cf9b9b89be330f512e1cac0d76c

**Comment by hay-kot** [comment] 2023-01-07 17:43
Didn't mean to close this, whoops!

---

@articuno1au, did you do the following? 

> To use the fix, be sure to
> 
> - Delete your current PWA installation
> - Clear cookies and storage for the website.

**Comment by articuno1au** [comment] 2023-01-08 00:21
> Didn't mean to close this, whoops!
> 
> @articuno1au, did you do the following?
> 
> > To use the fix, be sure to
> > 
> > * Delete your current PWA installation
> > * Clear cookies and storage for the website.

Yeah, I cleared data. ~~I just revalidated and am still seeing the same problem.~~

Scrub that. It seems to be resolved. I had been logging in then installing the PWA. I installed the PWA then logged in and it started working. I've tested a bunch of times, still working without issue. Not sure why that would make a difference.. Lgtm.

**Comment by SimSon2710** [comment] 2023-01-08 11:27
- Android 11, Samsung S10
- Firefox 108.2.0
- latest mealie nightly: v1.0.0beta-5 (container updated on 07.01.22) running on Ubuntu behind SWAG proxy

I can't confirm that it works :/

I uninstalled the PWA, deleted all browser data in firefox, installed the PWA w/o prior login and then logged in inside the PWA. This worked better than before, but when I closed the PWA and tried to reenter, mealie first asks me to enter my credentials, but then the screen turns blank as before.

**Comment by articuno1au** [comment] 2023-01-08 15:05
@SimSon2710 - Just for isolation testing, do you want to try again with a clean browser like Chrome or Vivaldi? I found some weird caching stuff with the PWA.

**Comment by SimSon2710** [comment] 2023-01-08 15:58
@articuno1au - I just tried both, completely new and clean installation of Vivaldi and Chrome, but the issue persist :/

**Comment by articuno1au** [comment] 2023-01-08 16:33
Worth a try. I can't replicate on my end I'm sorry. Good luck getting it sorted.

**Comment by hay-kot** [comment] 2023-01-08 19:10
> I just tried both, completely new and clean installation of Vivaldi and Chrome, but the issue persist :/

Up until the most recent builds I've been able to replicate the issue but now the PWA works as expected. As such, there's not much else I can do without any kind of ability to reproduce the issue. I would make sure / try the following

- You've got the latest frontend container (nightly).
- You've restarted your container since updating
- Verify your browser isn't deleting cookies and session data on exit of the PWA (common in firefox)
- Delete all installed versions of the PWA and clear session/cookies before re-installing
- Try the PWA on the demo site and see if the same issue occurs https://demo.mealie.io/

If none of that works, I'd need to get some information from your browser console on your phone which is a whole thing... Let me know!

**Comment by Zipties** [comment] 2023-01-08 19:58
> > This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
> 
> Good bot.
> 
> The issue is still relevant though! I just reproduced it with a fresh nightly (beta3) installation following the step I outlined above.

Same here on the latest nightly. 

@hay-kot are you still looking for someone to send debug logs?

**Comment by SimSon2710** [comment] 2023-01-27 19:17
Sorry I haven't answered anymore, but I was lost under a heap of work. I just updated mealie, and now it seems to work fine!

**Comment by m10x** [comment] 2023-02-03 15:52
It works now for us, too! :) Thank you

**Closed as completed** 2023-02-05 19:10 UTC
Labels: bug, help wanted, bug: confirmed
