### ISSUE TITLE
[mealie-nightly] - User management update gives unexpected error

### ISSUE THREAD

**Issue by aberlaas** [mealie-recipes/mealie#1319] opened 2022-05-31 07:37 UTC
As Admin, when I try to update user permission preferences, I got "An unexpected error occured".

Here is the log :

```
ERROR: 31-May-22 09:30:10 	__init__() missing 2 required positional arguments: 'name' and 'user_id'
Traceback (most recent call last):
  File "/app/mealie/db/models/_model_utils/helpers.py", line 42, in safe_call
    return func(**get_valid_call(func, dict_args))
TypeError: __init__() missing 2 required positional arguments: 'name' and 'user_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/mealie/routes/_base/mixins.py", line 96, in update_one
    item = self.repo.update(item_id, data)  # type: ignore
  File "/app/mealie/repos/repository_generic.py", line 187, in update
    entry.update(session=self.session, **new_data)  # type: ignore
  File "/app/mealie/db/models/_model_utils/auto_init.py", line 162, in wrapper
    instances = handle_one_to_many_list(session, get_attr, relation_cls, val)
  File "/app/mealie/db/models/_model_utils/auto_init.py", line 99, in handle_one_to_many_list
    new_elems = [safe_call(relation_cls, elem, session=session) for elem in elems_to_create]
  File "/app/mealie/db/models/_model_utils/auto_init.py", line 99, in <listcomp>
    new_elems = [safe_call(relation_cls, elem, session=session) for elem in elems_to_create]
  File "/app/mealie/db/models/_model_utils/helpers.py", line 44, in safe_call
    return func(**dict_args)
TypeError: __init__() missing 2 required positional arguments: 'name' and 'user_id'
```

**Comment by hay-kot** [comment] 2022-05-31 16:37
There is a bug reporting template. Please use that moving forward. 

I was unable to reproduce this using the latest build. Can you provide some more information on what you were doing? What is a the exact process to me to replicate your issue?

**Comment by aberlaas** [comment] 2022-05-31 16:53
My bad, I missed the template this time...

Trying to reproduce it, I think this is related to editing **another group** user details

To reproduce the issue:
- Log with admin privilege
- Go to "Parameters"
- Go to "Users" tab
- Click on **another group** user to edit user details
- Change any permission
- Click on "Update"

**Comment by hay-kot** [comment] 2022-05-31 17:01
I still can't replicate it locally or on the demo site. 

Can you replicate it on the demo site?

**Comment by aberlaas** [comment] 2022-05-31 17:10
Indeed, I can't reproduce it on demo site.
I can't neither reproduce it locally after creating a new user with another group.
Really strange !

**Comment by hay-kot** [comment] 2022-05-31 18:56
Weird, closing for now. Feel free to reopen if you can reproduce the error.

**Closed as completed by hay-kot** 2022-05-31 18:56 UTC
Labels: bug, can't reproduce

**Comment by aberlaas** [comment] 2022-05-31 22:15
Opening the database, I can see that the user causing problem is the only one with a different cache_key.
Its cache_key is ePyO when others are 1234.
Any idea ?
