### ISSUE TITLE
receipt from bettybossi.ch doesn't work

### ISSUE THREAD

**Issue by marcobischoff** [mealie-recipes/mealie#1900] opened 2022-12-14 22:22 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

When I try to add a recipe from bettybossi.ch (https://www.bettybossi.ch/de/Rezept/ShowRezept/BB_CZ14200331_0119A-40-de) I get an error.

Maybe an update to the latest version of the scraper could solve this issue.

### Deployment

Docker (Linux)

### Mealie Version

v1.0.0beta-5

**Comment by hay-kot** [comment] 2022-12-29 22:14
This site isn't listed as a supported site in the scraper library and they don't appear to provide any Schema information. Since this is more an issue with the scraper library than Mealie I'm going to close this issue. Thanks!

**Comment by marcobischoff** [comment] 2022-12-29 23:25
The site is listed: Please look at [Scrapers available for](https://github.com/hhursev/recipe-scrapers#scrapers-available-for) it is listed on the 20th line https://bettybossi.ch/

In the HTML I found this:

`

<script type="application/ld+json">{"@context":"http://schema.org","author":{"name":"Betty Bossi","@type":"Organization"},"publisher":{"name":"Betty Bossi","@type":"Organization"},"image":["https://www.bettybossi.ch/rdbimg/bb_cz14200331_0119a/bb_cz14200331_0119a_r01_v005_x0010.jpg","https://www.bettybossi.ch/rdbimg/bb_cz14200331_0119a/bb_cz14200331_0119a_r01_v004_x0020.jpg","https://www.bettybossi.ch/rdbimg/bb_cz14200331_0119a/bb_cz14200331_0119a_r02_v003_x0020.jpg","https://www.bettybossi.ch/rdbimg/bb_cz14200331_0119a/bb_cz14200331_0119a_r01_v004_x0010.jpg","https://www.bettybossi.ch/rdbimg/bb_cz14200331_0119a/bb_cz14200331_0119a_r02_v003_x0010.jpg","https://www.bettybossi.ch/rdbimg/bb_cz14200331_0119a/bb_cz14200331_0119a_r02_v001_x0020.jpg","https://www.bettybossi.ch/rdbimg/bb_cz14200331_0119a/bb_cz14200331_0119a_r02_v002_x0010.jpg","https://www.bettybossi.ch/rdbimg/bb_cz14200331_0119a/bb_cz14200331_0119a_r02_v001_x0010.jpg"],"name":"Cornflakes-Schoggi-Häufchen","description":"Möchtest du blitzschnell eine süsse Köstlichkeit auf den Tisch zaubern? Dann sind diese Cornflakes-Häufchen perfekt.","keywords":"Butter, Schokolade, Vanillezucker, Cornflakes","prepTime":"PT30M","totalTime":"PT30M","recipeYield":"4 Personen","recipeCategory":"Dessert","recipeCuisine":"Dessert","recipeIngredient":["100 g Butter","200 g dunkle Schokolade oder Milchschokolade","0.5 Päckli Vanillezucker","80 g Cornflakes"],"nutrition":{"calories":"108 kcal","fatContent":"8 g","carbohydrateContent":"9 g","proteinContent":"1 g","servingSize":"1 Stück","@type":"NutritionInformation"},"suitableForDiet":["https://schema.org/VegetarianDiet"],"recipeInstructions":[{"position":1,"text":"Butter in einer Pfanne schmelzen. Schokolade fein hacken, mit dem Vanillezucker zur Butter geben, unter Rühren schmelzen, etwas abkühlen.","@type":"HowToStep"},{"position":2,"text":"Cornflakes unter die noch flüssige Masse mischen. Masse mit 2 Tee­löffeln als Häufchen auf ein mit Backpapier belegtes Blech setzen. Guetzli kühl stellen, bis die Schokolade fest ist.","@type":"HowToStep"}],"datePublished":"2020-03-26","aggregateRating":{"ratingCount":1,"reviewCount":0,"ratingValue":5.00,"worstRating":1,"bestRating":5,"@type":"AggregateRating"},"@type":"Recipe"}</script><meta name=robots content="max-image-preview:large">
--
  |  

`

**Comment by hay-kot** [comment] 2022-12-29 23:30
Ahh, My bad. Thanks for following up, looks like something is happening during the cleaning process that's throwing an error. Will give it another look.

**Comment by michael-genson** [comment] 2023-12-10 23:24
I confirmed this is an issue with the recipe scrapers package. Even on the latest version it can't scrape from this site. I tried a few different recipes

**Closed as completed by michael-genson** 2023-12-10 23:24 UTC
Labels: bug, scraper, bug: confirmed
