### ISSUE TITLE
[v1.0.0b] - Shopping list sort order not saved when dragged

### ISSUE THREAD

**Issue by patrickheeney** [mealie-recipes/mealie#1352] opened 2022-06-06 21:23 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Dragging a shopping list item to change it's position doesn't save. Also seems to be a UX issue with the drag targets or timings as its a bit glitchy to reorder.

There are a few other issues, I might have to open new issue but they are related to the shopping list. 

1. The Copy as Text feature doesn't take into account the labels when turned on. 
2. The Copy as Text doesn't use the position of the items in the list, reverts to the original which may be because the new sort order is never saved.
3. It seems like you can drag when the label sort is turned on but dragging within each label doesn't work. 

https://user-images.githubusercontent.com/1407228/172237559-da60b38f-3c14-481c-bcb5-6e4c298cf24f.mp4

### Deployment

Docker (Linux)

**Comment by PFischbeck** [comment] 2022-08-22 20:45
> 1. The Copy as Text feature doesn't take into account the labels when turned on.

I'm not sure what you mean by the first point. Do you mean that the order in the copied text should be according to the labels, or do you also mean that there should be the labels within the copied text, separating different sublists?

**Comment by patrickheeney** [comment] 2022-08-22 20:55
@PFischbeck The former I think. I expected this output:

```
Black Vinegar
Lime Juice
Chili Powder
```

but instead I got the result on the right:

![Screen Shot 2022-08-22 at 1 47 48 PM](https://user-images.githubusercontent.com/1407228/186016057-8d1dfd06-9e15-4ca5-8710-33483b023adc.png)

It would be nice if the labels were applied to the text output as well. This would make the text identical to what appears on screen. Something like this: (this is a separate suggestion from what I was referring to)

```
Center
Black Vinegar
Lime Juice

Bulk Bin
Chili Powder
```

**Comment by hay-kot** [comment] 2022-10-22 04:30
Hey! The main issue here is resolved in

- #1749

For your other items

> The Copy as Text feature doesn't take into account the labels when turned on.

This is by design, I use Keep to use shopping lists and adding the labels in the heading would not Copy/Paste well into the application. I could see a feature where if your sorted by labels the copy button dynamically adjusts, but it isn't something I'm going to work on. Happy to accept a PR for it though.

> The Copy as Text doesn't use the position of the items in the list, reverts to the original which may be because the new sort order is never saved.

Pretty sure this is fixed for the main issue, but It's sort of unclear. If you try the new nightly after the PR is merged you're welcome to submit another issue with a reproducible example. 

> It seems like you can drag when the label sort is turned on but dragging within each label doesn't work.

This would be extremely difficult to implement, and not something that I'm interested in implementing in the app. 

Thanks!

**Closed as completed** 2022-10-22 04:35 UTC
Labels: bug, bug: confirmed
