### ISSUE TITLE
[v1.0.0b] - Login Sessions Fail to Persist Even When Using "Remember Me"

### ISSUE THREAD

**Issue by articuno1au** [mealie-recipes/mealie#1816] opened 2022-11-13 05:56 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I am forced to re-authenticate whenever the browser or PWA is closed.

Initially I had configured `TOKEN_TIME` to **762**, but noticed I had to login each time I re-opened my browser. I subsequently removed this configuration to test with the defaults. I'm still required to authenticate each time I log in.

Things tested

1. Multiple browsers - Linux (Vivaldi, Firefox, Chromium), Android (PWA through Vivaldi, Vivaldi, Firefox)
2. Checking the "Remember Me" checkbox (tested with all the above)
3. Bypassing my Traefik Load Balancer

I also took a moment to review the cookies
`auth.strategy` is set to **local**. `auth._token_experiation.local` had a cookie expiry of **+1 Year**, and what appears to be a Unix Timestamp of **1668490427000** which translates to **Tuesday, 15 November 2022 5:33:47 AM**. `auth._token.local` has a cookie expiry of **+1 Year** and a **Bearer** value (that I won't share for obvious reasons).

When closing the browser, the cookies persist with `auth.strategy`, `auth._token_experiation.local` and `auth._token.local` remaining unchanged. There's an additional cookie present in `auth.redirect` with a value of **%2Frecipes%2Fall**, which appears to the the post authentication redirect.

I'm not sure what's going wrong here. Please let me know if you need anything additional from to help with this one. It's driving my slightly loopy.

### Deployment

Docker (Linux)

### Deployment Details

Debian Bookworm with Docker 1.0.0b5 of Mealie.

Running Traefik in front as a load balancer. It's adding SSL and the following cookie configurations
```	-l traefik.http.middlewares.hsts.headers.BrowserXssFilter="true" \
	-l traefik.http.middlewares.hsts.headers.ContentTypeNosniff="true" \
	-l traefik.http.middlewares.hsts.headers.forcestsheader="true" \
	-l traefik.http.middlewares.hsts.headers.customFrameOptionsValue="SAMEORIGIN" \
	-l traefik.http.middlewares.hsts.headers.referrerPolicy="same-origin" \
	-l traefik.http.middlewares.hsts.headers.sslRedirect="true" \
	-l traefik.http.middlewares.hsts.headers.STSIncludeSubdomains="true" \
	-l traefik.http.middlewares.hsts.headers.STSPreload="true" \
	-l traefik.http.middlewares.hsts.headers.STSSeconds="315360000" \```

**Comment by SimSon2710** [comment] 2022-11-14 06:23
I'm dealing with the same problem on different browsers and devices. I think this could also be the reason that the android web app only shows a blank white screen.

**Comment by VL-Renegade** [comment] 2022-11-15 08:55
Same issue here, but when checking the expire settings of the cookies, it actually shows they are only valid until the browsersession is closed

**Comment by tuxthepenguin84** [comment] 2022-11-17 21:07
Having the same issue as well, noticed it on beta 4 and 5 running docker.

Edit: If I leave my browser session open with Mealie up I've noticed my sessions last longer, possibly for the life of the token. However if I close my browser I will (shortly?) have to sign back in.

**Comment by rakuri255** [comment] 2022-11-19 15:17
Have the same issue.
TOKEN_TIME just not work. You have to login every session again.

**Comment by ulimanaio** [comment] 2022-12-20 12:32
Same for me. 
v1.0.0beta-5

**Comment by Opethel** [comment] 2023-01-02 01:18
Seeing the same issue, v1.0.0beta-5

**Comment by hay-kot** [comment] 2023-01-03 03:59
Sorry everyone, I know this issue has been going on for some time and I've been rather quiet.

It is quite annoying and I can reproduce the error, though I've spent quite some time trying to track down why this is occurring. In particular I can't really get it to happen in development, so I'm guessing it has to do with SSR, but I'm not entirely sure.

The plugin we use for frontend session management doesn't give a lot of options for managing authorization, so I may end up needing to write a custom plugin which may take some time.

The next thing I'm going to try is writing a custom plugin that uses cookie based authorization with an explicit experation which will hopefully solve the persistence problem.

Thanks for your patience!

**Comment by hay-kot** [comment] 2023-01-04 01:51
> The next thing I'm going to try is writing a custom plugin that uses cookie based authorization with an explicit expiration which will hopefully solve the persistence problem.

Okay, that was a lie. I stumbled across [this issue](https://github.com/nuxt-community/auth-module/issues/1332) in the repo which I think _may_ be related, but again I'm having trouble verifying that issues as it seems to be inconsistent. 

I just merged #1918, which adjust the cookie parameters and may solve the issue. If you can, grab the latest nightly after the build finishes and give it a test drive and let me know if the issue persists!

May also be related to #1077, but that's only based on a gut feeling. 

--- 

Okay, #1982 may be the actual fix. This for sure looks like an issue with SSR where the cookies are not being passed to the axios client so when it tries to verify that it can access the user it fails.

**Comment by hay-kot** [comment] 2023-01-04 15:40
I'm got some confirmations on discord that this issue is resolved on the latest nightly image.

To use the fix, be sure to

1. Delete your current PWA installation
2. Clear cookies and storage for the website.

After that things _should_ work as expected. Please report back good or bad results!

**Comment by articuno1au** [comment] 2023-01-06 05:22
Hey @hay-kot,

Sorry, it took me a minute to get to testing this.

It's working on my desktop and mobile. I can't confirm it's fixed on the PWA though.

Whenever I re-open the PWA, the login interface appears for a half second, then it's replaced with a solid white screen that I can't interact with. I can refresh the page, but it repeats the behaviour. I just went through the issue backlog and spotted #1077 (then saw you mentioned it too..). I wasn't encountering this previously, so it's a new behaviour.

I've blown away all the stored data for the app (both cookies, and Apps), but the behaviour continues.

I'm guessing the issue at hand is fixed, but I can't confirm it due to this other issue.

Not sure if you want to close this one? Either way, let me know if there's anything else I can test, and thanks for taking a crack at it, very much appreciated :)

**Comment by hay-kot** [comment] 2023-01-06 19:24
> Sorry, it took me a minute to get to testing this.

Absolutely no problem, thanks for following up! 

> Not sure if you want to close this one? Either way, let me know if there's anything else I can test, and thanks for taking a crack at it, very much appreciated :)

Looks like _this_ issue has been resolved, so let's consolidate the PWA conversation into that one. 

---

If anyone on the latest nightly is still experiencing issues with persistent authentication **outside** of the PWA, please let me know here and we'll re-open the issue.

**Closed as completed by hay-kot** 2023-01-06 19:24 UTC
Labels: bug, bug: confirmed

**Comment by SimSon2710** [comment] 2023-01-08 11:03
I updated to latest nightly, and I can confirm, that the login session now lasts for longer! Thanks!
