### ISSUE TITLE
Recipes with duplicate names not being assigned unique keys/constraints in SQLite database.

### ISSUE THREAD

**Issue by orcsoul** [mealie-recipes/mealie#2431] opened 2023-06-27 21:10 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

When creating a recipe that has the same recipe name, but uses different tags and/or categories, Mealie is not assigning a unique key/constraint to the second (or third, etc) instance of a recipe with the same name.

```
[2023-06-27 15:48:26 -0500] [46] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/mealie/routes/recipe/recipe_crud_routes.py", line 155, in update_recipe
    recipe: Recipe = db.recipes.update(session, recipe_slug, data.dict())
  File "/app/mealie/db/db_base.py", line 149, in update
    session.commit()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    _emit_update_statements(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1000, in _emit_update_statements
    c = connection._execute_20(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: recipes.slug
[SQL: UPDATE recipes SET name=?, slug=?, date_updated=? WHERE recipes.id = ?]
[parameters: ('Duplicate Recipe', 'duplicate-recipe', '2023-06-27 15:48:26.666281', 121)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

### Deployment

Docker (Linux)

### Mealie Version

0.5.6

**Comment by hay-kot** [comment] 2023-06-27 21:14
I don't quite understand.

Are you saying that you are prevented from creating multiple recipes with the same name? Because that's intended behavior.

**Comment by orcsoul** [comment] 2023-06-27 21:17
Correct. If I wanted to say have multiple recipes for say "Butter Chicken" but each one is unique in it's preparation and ingredients but is differentiated by tags, I am unable to do this without assigning some arbitrary "-2" type affix that just looks wrong.

If this is intended behavior however, while unfortunate, I guess I can live with it and just have some ugly recipe names.

**Comment by RealFoxie** [comment] 2023-06-27 22:23
I thought the recipe 'name' (slug?) is only for the url, but you can change the title independently?

**Comment by hay-kot** [comment] 2023-06-27 22:30
> If this is intended behavior however, while unfortunate, I guess I can live with it and just have some ugly recipe names.

That's correct, this is intended so we can have "vanity" urls instead of /recipes/9f433ee5-5ffb-4a2d-ba48-879c64ff1e3. I find that adding adjectives before the recipe name helps distinguish between different types "Chewy Chocolate Chip Cookies" vs "Fluffy Chocolate Chip Cookies" but I don't have a huuuge number of recipes like some people so you may have mixed results.

> I thought the recipe 'name' (slug?) is only for the url, but you can change the title independently?

We don't allow for independent setting of the slug, it's kept in check with the name via a database hook. Though that's kind of an interesting idea to allow setting the slug manually. I think the Ghost Blog allows you to do that.

**Comment by hay-kot** [comment] 2023-09-07 21:10
Closing as this is expected behavior

**Closed as completed by hay-kot** 2023-09-07 21:10 UTC
