### ISSUE TITLE
[BUG] - Notes on Meal Planner are clickable, resulting in errors

### ISSUE THREAD

**Issue by boc-the-git** [mealie-recipes/mealie#3272] opened 2024-03-09 10:56 UTC
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

On the meal planner, when you add a note, it becomes clickable in the same way a recipe is; taking you to the same "recipe" page. Which results in an error because your note isn't (generally) a valid recipe.

![Meal_Plan_Note](https://github.com/mealie-recipes/mealie/assets/3479092/5bdca294-c586-49f6-bb94-b67d2c791487)

### Steps to Reproduce

1) Go to Meal Planner
2) Add a note
3) Go back to "view" mode
4) Click the note

### Please provide relevant logs

`"GET /api/recipes/<note title> HTTP/1.1" 404 Not Found`

### Mealie Version

Version
nightly
Build
[e84e5e2910d128911c0c2050a60dfdc205fe277a](https://github.com/mealie-recipes/mealie/commit/e84e5e2910d128911c0c2050a60dfdc205fe277a)

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment] 2024-03-09 18:07
Dupe of 

- https://github.com/mealie-recipes/mealie/issues/2350

**Closed as completed by hay-kot** 2024-03-09 18:07 UTC
Labels: bug, triage
