### ISSUE TITLE
[BUG] - Unable to Access Mealie Project Deployed via k3s on IPv6-only Server

### ISSUE THREAD

**Issue by killsnow** [mealie-recipes/mealie#2515] opened 2023-08-21 15:36 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

I encountered an issue while deploying the Mealie project using k3s on a server with only IPv6 connectivity. The project deploys successfully and starts, but I'm unable to access it. When attempting to access the project via curl localhost:3000/login, I receive the following error message:
```
json
Copy code
{
  "status": 500,
  "message": "connect ECONNREFUSED ::1:3000",
  "name": "Error"
}
```

on the browser
```
Server error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
```
Expected Behavior:
The Mealie project should be accessible when deployed via k3s on an IPv6-only server, just like when it is started locally using Docker Compose.

Actual Behavior:

The project starts successfully but is inaccessible, showing a connect ECONNREFUSED ::1:3000 error message.

Additional Information:

I have confirmed that the Docker Compose setup works correctly on my local machine.
The k3s deployment is successful, and the project starts without errors.
The issue seems to be related to IPv6 networking or configuration when deployed via k3s on an IPv6-only server.
Thank you for your assistance in addressing this issue. Let me know if you need any further information or assistance.

### Steps to Reproduce

Clone the latest code from the repository.
Navigate to the docker directory.
Build the Docker image using docker-compose -f omni.docker-compose.yml build.
Start the project locally using docker-compose -f omni.docker-compose.yml up -d.
Confirm the project starts without any issues and is accessible at localhost:3000/login.
Deploy the project using k3s on an IPv6-only server.
Attempt to access the project using curl localhost:3000/login or a web browser.
Expected Behavior:

### Please provide relevent logs

INFO: 21-Aug-23 22:01:01 	Database connection established.
INFO: 21-Aug-23 22:01:01 	Context impl SQLiteImpl.
INFO: 21-Aug-23 22:01:01 	Will assume non-transactional DDL.
INFO: 21-Aug-23 22:01:01 	Migration needed. Performing migration...
INFO: 21-Aug-23 22:01:01 	Context impl SQLiteImpl.
INFO: 21-Aug-23 22:01:01 	Will assume non-transactional DDL.
INFO: 21-Aug-23 22:01:01 	Running upgrade  -> 6b0f5f32d602, Initial tables
INFO: 21-Aug-23 22:01:02 	Running upgrade 6b0f5f32d602 -> 263dd6707191, convert quantity from integer to float
INFO: 21-Aug-23 22:01:02 	Running upgrade 263dd6707191 -> f1a2dbee5fe9, Add original_text column to recipes_ingredients
INFO: 21-Aug-23 22:01:02 	Running upgrade f1a2dbee5fe9 -> 59eb59135381, add tags to cookbooks
INFO: 21-Aug-23 22:01:03 	Running upgrade 59eb59135381 -> 09dfc897ad62, add require_all for cookbook filters
INFO: 21-Aug-23 22:01:03 	Running upgrade 09dfc897ad62 -> ab0bae02578f, Add use_abbreviation column to ingredients
INFO: 21-Aug-23 22:01:03 	Running upgrade ab0bae02578f -> f30cf048c228, add new webhook fields
INFO: 21-Aug-23 22:01:03 	Running upgrade f30cf048c228 -> 188374910655, add login_attemps and locked_at field to user table
INFO: 21-Aug-23 22:01:03 	Running upgrade 188374910655 -> 089bfa50d0ed, Add is_ocr_recipe column to recipes
INFO: 21-Aug-23 22:01:03 	Running upgrade 089bfa50d0ed -> 44e8d670719d, add extras to shopping lists, list items, and ingredient foods
INFO: 21-Aug-23 22:01:03 	Running upgrade 44e8d670719d -> 2ea7a807915c, add recipe_timeline_events table
INFO: 21-Aug-23 22:01:03 	Running upgrade 2ea7a807915c -> 1923519381ad, added recipe last made timestamp
INFO: 21-Aug-23 22:01:03 	Running upgrade 1923519381ad -> 167eb69066ad, add recipe_scale to shopping list item ref
INFO: 21-Aug-23 22:01:03 	Running upgrade 167eb69066ad -> 165d943c64ee, add related user to mealplan
INFO: 21-Aug-23 22:01:03 	Running upgrade 165d943c64ee -> ff5f73b01a7a, add missing foreign key and order indices
INFO: 21-Aug-23 22:01:04 	Running upgrade ff5f73b01a7a -> 16160bf731a0, add more indices necessary for search
INFO: 21-Aug-23 22:01:04 	Running upgrade 16160bf731a0 -> 5ab195a474eb, add normalized search properties
INFO: 21-Aug-23 22:01:04 	Running upgrade 5ab195a474eb -> b04a08da2108, added shopping list label settings
INFO: 21-Aug-23 22:01:05 	Running upgrade b04a08da2108 -> 38514b39a824, add auth_method to user table
INFO: 21-Aug-23 22:01:05 	Running upgrade 38514b39a824 -> b3dbb554ba53, postgres fuzzy search
WARNING: 21-Aug-23 22:01:05 	"get_all" method is deprecated; use "page_all" instead
INFO: 21-Aug-23 22:01:05 	Database contains no users, initializing...
INFO: 21-Aug-23 22:01:05 	Generating Default Group
INFO: 21-Aug-23 22:01:05 	Generating Default User
INFO: 21-Aug-23 22:01:05 	No food found with slug: 'dairy-products-and-dairy-substitutes' skipping fix
yarn run v1.22.19
$ nuxt start -p 3000
ℹ [HPM] Proxy created: api  -> http://localhost:9000
ℹ [HPM] Proxy rewrite rule created: "api" ~> "/api"
ℹ [HPM] Proxy created: /api  -> http://localhost:9000
ℹ [HPM] Proxy created: /docs  -> http://localhost:9000
ℹ [HPM] Proxy created: /openapi.json  -> http://localhost:9000
ℹ Listening on: http://10.42.0.186:3000/
INFO:     Started server process [15]
INFO:     Waiting for application startup.
INFO: 21-Aug-23 22:01:15 	-----SYSTEM STARTUP----- 

INFO: 21-Aug-23 22:01:15 	------APP SETTINGS------
INFO: 21-Aug-23 22:01:15 	{
    "PRODUCTION": true,
    "BASE_URL": "http://localhost:8080",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
INFO:     Application startup complete.
    "GIT_COMMIT_HASH": "",
    "ALLOW_SIGNUP": true,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DB_PROVIDER": {
        "data_dir": "/app/data",
        "prefix": ""
    },
    "DEFAULT_GROUP": "Home",
    "DEFAULT_EMAIL": "changeme@email.com",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
}
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO:     10.42.0.1:53538 - "GET / HTTP/1.1" 404 Not Found

 ERROR  connect ECONNREFUSED ::1:3000

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1481:16)

 ERROR  connect ECONNREFUSED ::1:3000

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1481:16)

### Mealie Version

commit d8a6f90

### Deployment

Other

### Additional Deployment Details

NAME     STATUS   ROLES                  AGE    VERSION        INTERNAL-IP   EXTERNAL-IP      OS-IMAGE           KERNEL-VERSION      CONTAINER-RUNTIME
master   Ready    control-plane,master   190d   v1.25.6+k3s1   10.0.4.14                                 Ubuntu 20.04 LTS   5.4.0-132-generic   containerd://1.6.15-k3s1
node1    Ready    <none>                 190d   v1.25.6+k3s1   10.0.4.14                                 Ubuntu 20.04 LTS   5.4.0-132-generic   containerd://1.6.15-k3s1

**Comment by Bibz87** [comment] 2023-10-18 00:43
For what it's worth, I'm running Mealie on my K3s cluster using an Ingress that points to a Service. The main difference is that my cluster runs IPv4.

So far, haven't had any issues.

**Comment by hay-kot** [comment] 2024-01-20 16:19
Dupe of https://github.com/mealie-recipes/mealie/issues/2440#issuecomment-1902165418

If you're still seeing this issue with the latest deployment please fill out another issue. Thanks!

**Closed as completed by hay-kot** 2024-01-20 16:19 UTC
Labels: bug, triage
