### ISSUE TITLE
[BUG] - Restoring mealie 2.0 does not work. Users are imported before households

### ISSUE THREAD

**Issue by Bretterteig** [mealie-recipes/mealie#4433] opened 2024-10-24 08:44 UTC
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I wanted to migrate my Mealie instance from sqlite to postgres. However, I cannot restore the created backup. It seems the new households feature is not yet properly implemented in the restore. 

It tries to import users before households, leading to a FK error as the households do not yet exist.

### Steps to Reproduce

1) Create a backup
2) Delete DB
3) Restore

### Please provide relevant logs

sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "users" violates foreign key constraint "fk_users_household_id"
DETAIL:  Key (household_id)=(ec8b8b72-1cd1-4081-80f0-fec7adae6f52) is not present in table "households".

### Mealie Version

ghcr.io/mealie-recipes/mealie:latest, version 2.0.0, Production
Build [a7c8b33cca37882f687a0528f93631545de74f1d](https://github.com/mealie-recipes/mealie/commit/a7c8b33cca37882f687a0528f93631545de74f1d)

### Deployment

Unraid

**Comment by boc-the-git** [comment] 2024-10-24 09:06
Please get your version details from the settings page.

But yea, from the logs, this error seems to support your hypothesis.

**Comment by Bretterteig** [comment] 2024-10-24 10:34
> Please get your version details from the settings page.
> 
> But yea, from the logs, this error seems to support your hypothesis.

I updated the issue with the version details

**Comment by michael-genson** [comment] 2024-10-24 13:09
Would you be able to provide your backup file for testing?

**Comment by michael-genson** [comment] 2024-10-24 13:53
I have a potential fix for this, but I can't reproduce the issue so I'm not sure

**Comment by michael-genson** [comment] 2024-10-24 17:56
Was able to reproduce with Bretterteig's backup!

**Comment by michael-genson** [comment] 2024-10-24 18:20
https://github.com/mealie-recipes/mealie/pull/4444 should fix this. FYI if you want to fix this manually before this is merged (or you don't want to switch to nightly/wait for a release) you can do the following:

1. Run the following on your postgres db: `SET session_replication_role = 'replica';`
2. Do the backup restore as normal, through Mealie
3. Run the following on your postgres db: `SET session_replication_role = 'origin';`

This will disable foreign key checks during the restore, then re-enable them. The linked PR will do this for you automatically.

**Comment by Bretterteig** [comment] 2024-10-24 19:29
> #4444 should fix this. FYI if you want to fix this manually before this is merged (or you don't want to switch to nightly/wait for a release) you can do the following:
> 
> 1. Run the following on your postgres db: `SET session_replication_role = 'replica';`
> 2. Do the backup restore as normal, through Mealie
> 3. Run the following on your postgres db: `SET session_replication_role = 'origin';`
> 
> This will disable foreign key checks during the restore, then re-enable them. The linked PR will do this for you automatically.

I was not able to restore the backup that I gave you earlier with this method. I got the same FK error as before

**Comment by michael-genson** [comment] 2024-10-24 19:36
Ah you know what it probably doesn't work because that's only for the current session. Try this:

`ALTER ROLE mealie SET session_replication_role = 'replica';`

Then restart the database container. Then, when you're done:

`ALTER ROLE mealie SET session_replication_role = 'origin';`

And restart the container again.

**Comment by Bretterteig** [comment] 2024-10-25 08:59
That did the trick, thanks!

**Closed as completed** 2024-10-29 12:43 UTC
Labels: bug, bug: confirmed
