### ISSUE TITLE
[BUG] - Cannot Download Recipe(s)

### ISSUE THREAD

**Issue by tumtumsback** [mealie-recipes/mealie#3095] opened 2024-02-01 17:23 UTC
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When I click on 'Download' on a recipe, it does nothing. I wanted to download a Mealie recipe, and give the ZIP to a friend, so that they could import the ZIP into their Mealie, but it just won't download.

### Steps to Reproduce

1) Open recipe
2) Click ... > Download
3) Does nothing

### Please provide relevant logs

INFO:     192.168.29.230:59323 - "POST /api/recipes/shrimp-fettuccine-alfredo/exports HTTP/1.1" 200 OK
INFO:     192.168.29.230:59323 - "GET /api/recipes/shrimp-fettuccine-alfredo/exports/zip?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzbHVnIjoic2hyaW1wLWZldHR1Y2NpbmUtYWxmcmVkbyIsImV4cCI6MTcwNjgwOTkxNX0.sLcmPW4e1l60K2LSy1gEqEUCvdnFx4I-x7OuhsKTDK0 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/responses.py", line 323, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/.temp/my_zip_archive.zip'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/responses.py", line 326, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path /app/data/.temp/my_zip_archive.zip does not exist.

### Mealie Version

**Details**
Version: v1.1.0
Build: 
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.53.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: error

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment] 2024-02-01 17:32
Can confirm, download seems to be broken 

@tumtumsback in the meantime before we issue a fix for that. If your mealie instance is public your friend should be able to scrape your recipe of your mealie with his mealie instance. If not public, i am pretty sure this should work with share links as well

**Comment by silentnoodle3** [comment] 2024-02-01 18:01
Thanks for confirming so quick, you guys are amazing. @Kuchenpirat I can confirm that using a share link from one Mealie instance and importing on another worked - the only thing that did not scrape and come over was the image file. I will watch this issue and use the workaround for now.

**Comment by boc-the-git** [comment] 2024-02-04 10:21
Looked into this briefly.. Definitely don't have the full picture in my head as yet.

The path `/app/data/.temp/my_zip_archive.zip` is coming from https://github.com/mealie-recipes/mealie/blob/292672601c783a1beb88b8e3ee5d161ff194ce78/mealie/core/dependencies/dependencies.py#L210

Which is almost certainly getting called from here: https://github.com/mealie-recipes/mealie/blob/292672601c783a1beb88b8e3ee5d161ff194ce78/mealie/routes/recipe/recipe_crud_routes.py#L117-L133

I haven't looked into how all the 3rd party libraries operate, though I note the error log seems to be using starlette a lot.

**Comment by boc-the-git** [comment] 2024-02-04 10:33
Possibly of interest.. in a dev container, I get this CORS error as below. I don't get that on my production instance. It's likely not relevant, but just dumping here as an FYI.

![image](https://github.com/mealie-recipes/mealie/assets/3479092/1427466a-1ecb-4e18-8bc6-6604c77fbd5f)

**Comment by boc-the-git** [comment] 2024-02-04 10:52
Last thing I'll add for now.. 

```
mealie    | INFO:     xxx.xx.xxx.xx:0 - "POST /api/recipes/one-pan-baked-butter-chicken/exports HTTP/1.1" 200 OK
mealie    | INFO: 04-Feb-24 21:48:52    temp_path=/app/data/.temp/my_zip_archive.zip, filename=one-pan-baked-butter-chicken.zip
mealie    | INFO:     xxx.xx.xxx.xx:0 - "GET /api/recipes/one-pan-baked-butter-chicken/exports/zip?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzbHVnIjoib25lLXBhbi1iYWtlZC1idXR0ZXItY2hpY2tlbiIsImV4cCI6MTcwNzA0NTUzMX0.AYcSWKhSYUCTMGkzzsoyWUyOrhJCrQVOT5ubZrC86lk HTTP/1.1" 500 Internal Server Error
<error message seen above continues from here>
```

This is an output of the variables immediately before this line.. I'm assuming it could be relevant/useful in some way.
https://github.com/mealie-recipes/mealie/blob/292672601c783a1beb88b8e3ee5d161ff194ce78/mealie/routes/recipe/recipe_crud_routes.py#L133

Need to look into the FileResponse call, and also whether the write methods of the ZipFile class have actually done something.

**Comment by nephlm** [comment] 2024-05-01 05:24
I did a bit of debugging on this.

https://github.com/mealie-recipes/mealie/blob/ee87a14401c7d2c18d19947d283364d2419415a8/mealie/routes/recipe/recipe_crud_routes.py#L119

Part one of the issue is `temporary_zip_path` which is defined as:

https://github.com/mealie-recipes/mealie/blob/ee87a14401c7d2c18d19947d283364d2419415a8/mealie/core/dependencies/dependencies.py#L208-L215

Which means when `get_recipe_as_zip` goes out of scope, the file that was created is deleted.  If you dig into `FileResponse` you'll see that it doesn't actually return the file before `get_recipe_as_zip` exits.
  
The `FileResponse` constructor doesn't actually read the file, but only sets the path and filename as an instancevar.  The `FileRespnse` instance is returned to the code which called `get_recipe_as_zip`, which is essentially the starlette router.  The router will eventually go on to call `FileResponse.__call__()`, but by then `get_recipe_as_zip` has exited and `temporary_zip_path` has unlinked the zip file.  

I did some hacking and can empirically say that the file exists during `FileResponse.__init__()`, but not during `FileResponse.__call__()`.  I think it's highly likely that in between those two events `get_recipe_as_zip()` exits which causes the zip file to be unlinked. 

We're going to need to find some other way to clean up the zip file.  I expect we're going to have to lean on whatever causes data exports to expire, but I just started looking at the code, so I don't know what that is yet.

**Comment by nephlm** [comment] 2024-05-08 01:43
Both `temporary_zip_path` and `temporary_file` in `dependencies.py` use this mechanism, but `temporary_file` doesn't appear to be used by anything.  

`temporary_zip_file` is used by:
* `GET /api/recipes/{slug}/exports/zip` 
    * `mealie/routes/recipe/recipe_crud_routes.py.RecipeExportController.get_recipe_as_zip()`
    * This was confirmed and the genesis of this bug. 
* `POST /api/groups/migrations`  
    * `mealie/routes/groups/controller_migrations.py.GroupMigrationController.start_data_migration()`
* `POST /api/recipes/bulk-actions/export` 
    * `mealie/routes/recipe/bulk_actions.py.RecipeBulkActionController.bulk_export_recipes()`
* `POST /api/recipes/create-from-zip` 
    * `mealie/routes/recipe/recipe_crud_routes.py.RecipeController.create_recipe_from_zip()`

The other three endpoints use `temporary_zip_file` in a self contained way so they don't seem to be impacted when the path is unlinked, so the issue seems to be constrained to `GET /api/recipes/{slug}/exports/zip`.

The easiest thing would be to create a version of `temporary_zip_file` that doesn't unlink and then pass a background task into the  `FileResponse` that unlinks the file, but that will leave a brief time between when the zip file is created and when `FileResponse.__call__()` is completed during which the .zip file won't be cleaned up if something killed the system during that moment, but depending on how hard the system is killed, that is always true.

Refs:
https://github.com/tiangolo/fastapi/discussions/7148
https://stackoverflow.com/questions/64716495/how-to-delete-the-file-after-a-return-fileresponsefile-path
https://www.starlette.io/background/

**Closed as completed** 2024-05-20 22:53 UTC
Labels: bug, bug: confirmed

**Comment by badabing2005** [comment] 2025-09-07 01:30
Download seems to be broken again.
The downloaded file has this as the content.

```
{"detail":"Not authenticated"}
```

Let me know if you want me to create a separate ticket.
Version v3.1.2

I see there is an open issue on that.
#5763
